//
//  VocabularyData.swift
//  vocab-builder
//
//  Created by Michael Zhao on 1/16/26.
//

import Foundation

struct VocabularyWord: Codable, Identifiable {
    let id: Int
    let word: String
    let definition: String
}

struct VocabularyData {
    static let words: [VocabularyWord] = [
        VocabularyWord(id: 0, word: "Ephemeral", definition: "Lasting for a very short time"),
        VocabularyWord(id: 1, word: "Ubiquitous", definition: "Present everywhere at once"),
        VocabularyWord(id: 2, word: "Sanguine", definition: "Optimistic, especially in difficult situations"),
        VocabularyWord(id: 3, word: "Perfunctory", definition: "Done without care or interest"),
        VocabularyWord(id: 4, word: "Laconic", definition: "Using very few words"),
        VocabularyWord(id: 5, word: "Obsequious", definition: "Excessively eager to please"),
        VocabularyWord(id: 6, word: "Capricious", definition: "Given to sudden changes of mood"),
        VocabularyWord(id: 7, word: "Pernicious", definition: "Having a harmful effect, especially gradually"),
        VocabularyWord(id: 8, word: "Fastidious", definition: "Very attentive to detail and accuracy"),
        VocabularyWord(id: 9, word: "Gregarious", definition: "Fond of company; sociable"),
        VocabularyWord(id: 10, word: "Taciturn", definition: "Reserved; saying little"),
        VocabularyWord(id: 11, word: "Eloquent", definition: "Fluent and persuasive in speech"),
        VocabularyWord(id: 12, word: "Pragmatic", definition: "Dealing with things sensibly and realistically"),
        VocabularyWord(id: 13, word: "Resilient", definition: "Able to recover quickly from difficulties"),
        VocabularyWord(id: 14, word: "Tenacious", definition: "Holding firmly to something"),
        VocabularyWord(id: 15, word: "Astute", definition: "Having sharp judgment; shrewd"),
        VocabularyWord(id: 16, word: "Candid", definition: "Truthful and straightforward"),
        VocabularyWord(id: 17, word: "Diligent", definition: "Showing careful and persistent effort"),
        VocabularyWord(id: 18, word: "Arduous", definition: "Requiring great effort; difficult"),
        VocabularyWord(id: 19, word: "Benevolent", definition: "Well-meaning and kindly"),
        VocabularyWord(id: 20, word: "Cogent", definition: "Clear, logical, and convincing"),
        VocabularyWord(id: 21, word: "Disparate", definition: "Essentially different in kind"),
        VocabularyWord(id: 22, word: "Erudite", definition: "Having great knowledge or learning"),
        VocabularyWord(id: 23, word: "Frivolous", definition: "Not having serious purpose or value"),
        VocabularyWord(id: 24, word: "Galvanize", definition: "To shock or excite into action"),
        VocabularyWord(id: 25, word: "Hapless", definition: "Unfortunate; unlucky"),
        VocabularyWord(id: 26, word: "Impetuous", definition: "Acting quickly without thought"),
        VocabularyWord(id: 27, word: "Judicious", definition: "Having good judgment; sensible"),
        VocabularyWord(id: 28, word: "Keen", definition: "Eager; intellectually sharp"),
        VocabularyWord(id: 29, word: "Lethargic", definition: "Lacking energy; sluggish"),
        VocabularyWord(id: 30, word: "Meticulous", definition: "Showing great attention to detail"),
        VocabularyWord(id: 31, word: "Nonchalant", definition: "Casually calm and relaxed"),
        VocabularyWord(id: 32, word: "Opulent", definition: "Ostentatiously rich and luxurious"),
        VocabularyWord(id: 33, word: "Prudent", definition: "Acting with care and thought for the future"),
        VocabularyWord(id: 34, word: "Querulous", definition: "Complaining in a whining manner"),
        VocabularyWord(id: 35, word: "Reclusive", definition: "Avoiding the company of others"),
        VocabularyWord(id: 36, word: "Stoic", definition: "Enduring pain without complaint"),
        VocabularyWord(id: 37, word: "Trepidation", definition: "A feeling of fear about something"),
        VocabularyWord(id: 38, word: "Unctuous", definition: "Excessively flattering; oily"),
        VocabularyWord(id: 39, word: "Verbose", definition: "Using more words than needed"),
        VocabularyWord(id: 40, word: "Whimsical", definition: "Playfully quaint or fanciful"),
        VocabularyWord(id: 41, word: "Zealous", definition: "Having great energy for a cause"),
        VocabularyWord(id: 42, word: "Ambivalent", definition: "Having mixed feelings"),
        VocabularyWord(id: 43, word: "Brevity", definition: "Concise and exact use of words"),
        VocabularyWord(id: 44, word: "Cryptic", definition: "Having a hidden meaning; mysterious"),
        VocabularyWord(id: 45, word: "Dubious", definition: "Hesitating or doubting"),
        VocabularyWord(id: 46, word: "Emulate", definition: "To match or surpass by imitation"),
        VocabularyWord(id: 47, word: "Fervent", definition: "Having passionate intensity"),
        VocabularyWord(id: 48, word: "Gullible", definition: "Easily persuaded to believe"),
        VocabularyWord(id: 49, word: "Haughty", definition: "Arrogantly superior"),
        VocabularyWord(id: 50, word: "Innate", definition: "Inborn; natural"),
        VocabularyWord(id: 51, word: "Jaded", definition: "Tired or bored from overexposure"),
        VocabularyWord(id: 52, word: "Kindle", definition: "To arouse or inspire"),
        VocabularyWord(id: 53, word: "Lucid", definition: "Expressed clearly; easy to understand"),
        VocabularyWord(id: 54, word: "Mundane", definition: "Lacking interest; ordinary"),
        VocabularyWord(id: 55, word: "Novice", definition: "A person new to a field"),
        VocabularyWord(id: 56, word: "Obscure", definition: "Not clearly understood; hidden"),
        VocabularyWord(id: 57, word: "Palpable", definition: "Able to be touched or felt"),
        VocabularyWord(id: 58, word: "Quaint", definition: "Attractively unusual or old-fashioned"),
        VocabularyWord(id: 59, word: "Reverent", definition: "Feeling deep respect"),
        VocabularyWord(id: 60, word: "Serene", definition: "Calm and peaceful"),
        VocabularyWord(id: 61, word: "Transient", definition: "Lasting only a short time"),
        VocabularyWord(id: 62, word: "Unassuming", definition: "Not pretentious; modest"),
        VocabularyWord(id: 63, word: "Vivid", definition: "Producing powerful mental images"),
        VocabularyWord(id: 64, word: "Wary", definition: "Feeling cautious about dangers"),
        VocabularyWord(id: 65, word: "Abate", definition: "To become less intense"),
        VocabularyWord(id: 66, word: "Beguile", definition: "To charm or enchant deceptively"),
        VocabularyWord(id: 67, word: "Complacent", definition: "Smugly self-satisfied"),
        VocabularyWord(id: 68, word: "Deft", definition: "Neatly skillful and quick"),
        VocabularyWord(id: 69, word: "Elusive", definition: "Difficult to find or catch"),
        VocabularyWord(id: 70, word: "Frugal", definition: "Sparing with money or resources"),
        VocabularyWord(id: 71, word: "Gratuitous", definition: "Uncalled for; unwarranted"),
        VocabularyWord(id: 72, word: "Heretic", definition: "One who holds controversial opinions"),
        VocabularyWord(id: 73, word: "Immutable", definition: "Unchanging over time"),
        VocabularyWord(id: 74, word: "Jubilant", definition: "Feeling great happiness"),
        VocabularyWord(id: 75, word: "Kinetic", definition: "Relating to or resulting from motion"),
        VocabularyWord(id: 76, word: "Languid", definition: "Lacking energy; weak"),
        VocabularyWord(id: 77, word: "Malleable", definition: "Easily influenced; pliable"),
        VocabularyWord(id: 78, word: "Nascent", definition: "Just beginning to develop"),
        VocabularyWord(id: 79, word: "Obstinate", definition: "Stubbornly refusing to change"),
        VocabularyWord(id: 80, word: "Placid", definition: "Not easily upset; calm"),
        VocabularyWord(id: 81, word: "Quell", definition: "To put an end to; suppress"),
        VocabularyWord(id: 82, word: "Reticent", definition: "Not revealing one's thoughts"),
        VocabularyWord(id: 83, word: "Succinct", definition: "Briefly and clearly expressed"),
        VocabularyWord(id: 84, word: "Tangible", definition: "Perceptible by touch; clear"),
        VocabularyWord(id: 85, word: "Urbane", definition: "Suave and sophisticated"),
        VocabularyWord(id: 86, word: "Venerate", definition: "To regard with great respect"),
        VocabularyWord(id: 87, word: "Wistful", definition: "Having vague or regretful longing"),
        VocabularyWord(id: 88, word: "Anomaly", definition: "Something that deviates from normal"),
        VocabularyWord(id: 89, word: "Blithe", definition: "Showing casual indifference"),
        VocabularyWord(id: 90, word: "Clandestine", definition: "Kept secret; surreptitious"),
        VocabularyWord(id: 91, word: "Dauntless", definition: "Showing fearlessness"),
        VocabularyWord(id: 92, word: "Empirical", definition: "Based on observation or experience"),
        VocabularyWord(id: 93, word: "Fallacious", definition: "Based on a mistaken belief"),
        VocabularyWord(id: 94, word: "Garrulous", definition: "Excessively talkative"),
        VocabularyWord(id: 95, word: "Hackneyed", definition: "Overused; unoriginal"),
        VocabularyWord(id: 96, word: "Iconoclast", definition: "One who attacks cherished beliefs"),
        VocabularyWord(id: 97, word: "Jingoism", definition: "Extreme patriotism"),
        VocabularyWord(id: 98, word: "Kudos", definition: "Praise and honor received"),
        VocabularyWord(id: 99, word: "Lament", definition: "To express grief or regret"),
        VocabularyWord(id: 100, word: "Maverick", definition: "An independent-minded person"),
        VocabularyWord(id: 101, word: "Nefarious", definition: "Wicked or criminal"),
        VocabularyWord(id: 102, word: "Onerous", definition: "Involving heavy obligation"),
        VocabularyWord(id: 103, word: "Parsimonious", definition: "Extremely unwilling to spend"),
        VocabularyWord(id: 104, word: "Quixotic", definition: "Exceedingly idealistic; unrealistic"),
        VocabularyWord(id: 105, word: "Recalcitrant", definition: "Stubbornly uncooperative"),
        VocabularyWord(id: 106, word: "Sagacious", definition: "Having keen mental discernment"),
        VocabularyWord(id: 107, word: "Truculent", definition: "Eager to fight; aggressive"),
        VocabularyWord(id: 108, word: "Usurp", definition: "To seize power without authority"),
        VocabularyWord(id: 109, word: "Vacillate", definition: "To waver between different opinions"),
        VocabularyWord(id: 110, word: "Wanton", definition: "Deliberate and unprovoked"),
        VocabularyWord(id: 111, word: "Acumen", definition: "The ability to make good judgments"),
        VocabularyWord(id: 112, word: "Bolster", definition: "To support or strengthen"),
        VocabularyWord(id: 113, word: "Circumspect", definition: "Wary and unwilling to take risks"),
        VocabularyWord(id: 114, word: "Debilitate", definition: "To make weak; enfeeble"),
        VocabularyWord(id: 115, word: "Ebullient", definition: "Cheerful and full of energy"),
        VocabularyWord(id: 116, word: "Facetious", definition: "Treating serious issues with humor"),
        VocabularyWord(id: 117, word: "Germane", definition: "Relevant to the subject at hand"),
        VocabularyWord(id: 118, word: "Hegemony", definition: "Leadership or dominance"),
        VocabularyWord(id: 119, word: "Ignominious", definition: "Deserving public disgrace"),
        VocabularyWord(id: 120, word: "Juxtapose", definition: "To place side by side for contrast"),
        VocabularyWord(id: 121, word: "Kowtow", definition: "To act in a submissive manner"),
        VocabularyWord(id: 122, word: "Litigious", definition: "Tending to engage in lawsuits"),
        VocabularyWord(id: 123, word: "Morose", definition: "Sullen and ill-tempered"),
        VocabularyWord(id: 124, word: "Nebulous", definition: "Unclear, vague, or ill-defined"),
        VocabularyWord(id: 125, word: "Ostentatious", definition: "Showy; meant to impress"),
        VocabularyWord(id: 126, word: "Pedantic", definition: "Excessively concerned with details"),
        VocabularyWord(id: 127, word: "Quintessential", definition: "Representing the perfect example"),
        VocabularyWord(id: 128, word: "Rancorous", definition: "Characterized by bitterness"),
        VocabularyWord(id: 129, word: "Sycophant", definition: "A person who flatters for gain"),
        VocabularyWord(id: 130, word: "Terse", definition: "Sparing in the use of words"),
        VocabularyWord(id: 131, word: "Umbrage", definition: "Offense or annoyance"),
        VocabularyWord(id: 132, word: "Vindicate", definition: "To clear of accusation"),
        VocabularyWord(id: 133, word: "Winsome", definition: "Attractive or appealing"),
        VocabularyWord(id: 134, word: "Alacrity", definition: "Brisk and cheerful readiness"),
        VocabularyWord(id: 135, word: "Bellicose", definition: "Demonstrating aggression"),
        VocabularyWord(id: 136, word: "Cacophony", definition: "A harsh, discordant mixture of sounds"),
        VocabularyWord(id: 137, word: "Deleterious", definition: "Causing harm or damage"),
        VocabularyWord(id: 138, word: "Equanimity", definition: "Mental calmness and composure"),
        VocabularyWord(id: 139, word: "Fortuitous", definition: "Happening by chance"),
        VocabularyWord(id: 140, word: "Gregarious", definition: "Enjoying the company of others"),
        VocabularyWord(id: 141, word: "Harbinger", definition: "A person or thing that announces"),
        VocabularyWord(id: 142, word: "Idiosyncrasy", definition: "A distinctive individual characteristic"),
        VocabularyWord(id: 143, word: "Judicious", definition: "Having or showing good judgment"),
        VocabularyWord(id: 144, word: "Kismet", definition: "Destiny; fate"),
        VocabularyWord(id: 145, word: "Loquacious", definition: "Tending to talk a great deal"),
        VocabularyWord(id: 146, word: "Magnanimous", definition: "Very generous or forgiving"),
        VocabularyWord(id: 147, word: "Nihilism", definition: "Rejection of all moral principles"),
        VocabularyWord(id: 148, word: "Obfuscate", definition: "To render obscure or unclear"),
        VocabularyWord(id: 149, word: "Panacea", definition: "A solution for all difficulties"),
        VocabularyWord(id: 150, word: "Raconteur", definition: "A skilled storyteller"),
        VocabularyWord(id: 151, word: "Sanctimonious", definition: "Making a show of being moral"),
        VocabularyWord(id: 152, word: "Tantamount", definition: "Equivalent in effect"),
        VocabularyWord(id: 153, word: "Unequivocal", definition: "Leaving no doubt; clear"),
        VocabularyWord(id: 154, word: "Veracious", definition: "Speaking or representing the truth"),
        VocabularyWord(id: 155, word: "Watershed", definition: "A turning point"),
        VocabularyWord(id: 156, word: "Abstruse", definition: "Difficult to understand"),
        VocabularyWord(id: 157, word: "Burgeon", definition: "To begin to grow rapidly"),
        VocabularyWord(id: 158, word: "Confluence", definition: "A coming together"),
        VocabularyWord(id: 159, word: "Dichotomy", definition: "A division into two contrasting parts"),
        VocabularyWord(id: 160, word: "Engender", definition: "To cause or give rise to"),
        VocabularyWord(id: 161, word: "Furtive", definition: "Attempting to avoid notice"),
        VocabularyWord(id: 162, word: "Hedonist", definition: "One who pursues pleasure"),
        VocabularyWord(id: 163, word: "Impervious", definition: "Not allowing passage through"),
        VocabularyWord(id: 164, word: "Juggernaut", definition: "A huge, powerful force"),
        VocabularyWord(id: 165, word: "Labyrinthine", definition: "Like a maze; complicated"),
        VocabularyWord(id: 166, word: "Myriad", definition: "A countless number"),
        VocabularyWord(id: 167, word: "Nascent", definition: "Just beginning to develop"),
        VocabularyWord(id: 168, word: "Obtuse", definition: "Annoyingly slow to understand"),
        VocabularyWord(id: 169, word: "Prodigious", definition: "Remarkably great in extent"),
        VocabularyWord(id: 170, word: "Rapacious", definition: "Aggressively greedy"),
        VocabularyWord(id: 171, word: "Spurious", definition: "Not being what it appears to be"),
        VocabularyWord(id: 172, word: "Timorous", definition: "Showing nervousness or fear"),
        VocabularyWord(id: 173, word: "Unscrupulous", definition: "Having no moral principles"),
        VocabularyWord(id: 174, word: "Vapid", definition: "Offering nothing stimulating"),
        VocabularyWord(id: 175, word: "Whet", definition: "To sharpen or stimulate"),
        VocabularyWord(id: 176, word: "Apocryphal", definition: "Of doubtful authenticity"),
        VocabularyWord(id: 177, word: "Byzantine", definition: "Excessively complicated"),
        VocabularyWord(id: 178, word: "Conundrum", definition: "A confusing problem"),
        VocabularyWord(id: 179, word: "Dilettante", definition: "A person with superficial interest"),
        VocabularyWord(id: 180, word: "Enigmatic", definition: "Difficult to interpret; mysterious"),
        VocabularyWord(id: 181, word: "Fatuous", definition: "Silly and pointless"),
        VocabularyWord(id: 182, word: "Grandiose", definition: "Impressive but with pretension"),
        VocabularyWord(id: 183, word: "Hubris", definition: "Excessive pride or self-confidence"),
        VocabularyWord(id: 184, word: "Impugn", definition: "To dispute the truth of"),
        VocabularyWord(id: 185, word: "Juxtaposition", definition: "Placing things close together"),
        VocabularyWord(id: 186, word: "Kafkaesque", definition: "Marked by surreal distortion"),
        VocabularyWord(id: 187, word: "Lugubrious", definition: "Looking or sounding sad"),
        VocabularyWord(id: 188, word: "Machiavellian", definition: "Cunning and deceitful"),
        VocabularyWord(id: 189, word: "Obdurate", definition: "Stubbornly refusing to change"),
        VocabularyWord(id: 190, word: "Profligate", definition: "Recklessly wasteful"),
        VocabularyWord(id: 191, word: "Quandary", definition: "A state of uncertainty"),
        VocabularyWord(id: 192, word: "Refractory", definition: "Stubborn or unmanageable"),
        VocabularyWord(id: 193, word: "Soporific", definition: "Tending to induce sleep"),
        VocabularyWord(id: 194, word: "Trenchant", definition: "Vigorous and articulate"),
        VocabularyWord(id: 195, word: "Unflappable", definition: "Having composure in crisis"),
        VocabularyWord(id: 196, word: "Vitriolic", definition: "Filled with bitter criticism"),
        VocabularyWord(id: 197, word: "Weltschmerz", definition: "World-weariness; melancholy"),
        VocabularyWord(id: 198, word: "Xenophile", definition: "One attracted to foreign things"),
        VocabularyWord(id: 199, word: "Yeoman", definition: "A person who does reliable work"),
        VocabularyWord(id: 200, word: "Zeitgeist", definition: "The spirit of the times"),
        VocabularyWord(id: 201, word: "Aberration", definition: "A departure from what is normal"),
        VocabularyWord(id: 202, word: "Boorish", definition: "Rough and bad-mannered"),
        VocabularyWord(id: 203, word: "Caustic", definition: "Sarcastic in a bitter way"),
        VocabularyWord(id: 204, word: "Diatribe", definition: "A forceful verbal attack"),
        VocabularyWord(id: 205, word: "Eclectic", definition: "Deriving from various sources"),
        VocabularyWord(id: 206, word: "Feckless", definition: "Lacking initiative or strength"),
        VocabularyWord(id: 207, word: "Guileless", definition: "Innocent and without deception"),
        VocabularyWord(id: 208, word: "Histrionic", definition: "Overly theatrical or melodramatic"),
        VocabularyWord(id: 209, word: "Ineffable", definition: "Too great to be expressed in words"),
        VocabularyWord(id: 210, word: "Jocular", definition: "Fond of joking; humorous"),
        VocabularyWord(id: 211, word: "Knavery", definition: "Dishonest or unscrupulous acts"),
        VocabularyWord(id: 212, word: "Lurid", definition: "Unpleasantly bright; sensational"),
        VocabularyWord(id: 213, word: "Mendacious", definition: "Not telling the truth; lying"),
        VocabularyWord(id: 214, word: "Noxious", definition: "Harmful or poisonous"),
        VocabularyWord(id: 215, word: "Officious", definition: "Asserting authority annoyingly"),
        VocabularyWord(id: 216, word: "Pariah", definition: "An outcast"),
        VocabularyWord(id: 217, word: "Querulous", definition: "Complaining; whining"),
        VocabularyWord(id: 218, word: "Redoubtable", definition: "Formidable; commanding respect"),
        VocabularyWord(id: 219, word: "Sardonic", definition: "Grimly mocking or cynical"),
        VocabularyWord(id: 220, word: "Tortuous", definition: "Full of twists and turns"),
        VocabularyWord(id: 221, word: "Unctuous", definition: "Excessively smooth or smug"),
        VocabularyWord(id: 222, word: "Vicarious", definition: "Experienced through another"),
        VocabularyWord(id: 223, word: "Waffle", definition: "To speak vaguely or evasively"),
        VocabularyWord(id: 224, word: "Acerbic", definition: "Sharp and forthright"),
        VocabularyWord(id: 225, word: "Bifurcate", definition: "To divide into two branches"),
        VocabularyWord(id: 226, word: "Churlish", definition: "Rude in a mean-spirited way"),
        VocabularyWord(id: 227, word: "Desultory", definition: "Lacking a plan or purpose"),
        VocabularyWord(id: 228, word: "Ersatz", definition: "Not real or genuine"),
        VocabularyWord(id: 229, word: "Florid", definition: "Having a red or flushed complexion"),
        VocabularyWord(id: 230, word: "Gossamer", definition: "Very light, thin, and insubstantial"),
        VocabularyWord(id: 231, word: "Halcyon", definition: "Denoting a happy, golden time"),
        VocabularyWord(id: 232, word: "Insipid", definition: "Lacking flavor or interest"),
        VocabularyWord(id: 233, word: "Jettison", definition: "To throw away; abandon"),
        VocabularyWord(id: 234, word: "Kinship", definition: "Blood relationship; affinity"),
        VocabularyWord(id: 235, word: "Lissome", definition: "Thin, supple, and graceful"),
        VocabularyWord(id: 236, word: "Mellifluous", definition: "Sweet-sounding"),
        VocabularyWord(id: 237, word: "Neophyte", definition: "A person new to a subject"),
        VocabularyWord(id: 238, word: "Opaque", definition: "Not transparent; hard to understand"),
        VocabularyWord(id: 239, word: "Palliate", definition: "To make less severe"),
        VocabularyWord(id: 240, word: "Rescind", definition: "To revoke or cancel"),
        VocabularyWord(id: 241, word: "Surreptitious", definition: "Kept secret, especially because improper"),
        VocabularyWord(id: 242, word: "Tacit", definition: "Understood without being stated"),
        VocabularyWord(id: 243, word: "Umbrage", definition: "Offense; annoyance"),
        VocabularyWord(id: 244, word: "Verisimilitude", definition: "The appearance of being true"),
        VocabularyWord(id: 245, word: "Wan", definition: "Pale and giving the impression of illness"),
        VocabularyWord(id: 246, word: "Adroit", definition: "Clever or skillful"),
        VocabularyWord(id: 247, word: "Banal", definition: "So lacking in originality as to be obvious"),
        VocabularyWord(id: 248, word: "Convoluted", definition: "Extremely complex and difficult to follow"),
        VocabularyWord(id: 249, word: "Diminutive", definition: "Extremely or unusually small"),
        VocabularyWord(id: 250, word: "Efficacious", definition: "Successful in producing a desired result"),
        VocabularyWord(id: 251, word: "Flippant", definition: "Not showing a serious attitude"),
        VocabularyWord(id: 252, word: "Glib", definition: "Fluent but insincere"),
        VocabularyWord(id: 253, word: "Hermetic", definition: "Complete and airtight"),
        VocabularyWord(id: 254, word: "Inchoate", definition: "Just begun; not fully formed"),
        VocabularyWord(id: 255, word: "Jejune", definition: "Naive; lacking substance"),
        VocabularyWord(id: 256, word: "Limpid", definition: "Clear and transparent"),
        VocabularyWord(id: 257, word: "Mercurial", definition: "Subject to sudden changes of mood"),
        VocabularyWord(id: 258, word: "Nonplussed", definition: "Surprised and confused"),
        VocabularyWord(id: 259, word: "Oblique", definition: "Not straightforward; indirect"),
        VocabularyWord(id: 260, word: "Pellucid", definition: "Translucently clear"),
        VocabularyWord(id: 261, word: "Quotidian", definition: "Occurring every day; ordinary"),
        VocabularyWord(id: 262, word: "Recondite", definition: "Little known; abstruse"),
        VocabularyWord(id: 263, word: "Sanguinary", definition: "Involving or causing bloodshed"),
        VocabularyWord(id: 264, word: "Torpid", definition: "Mentally or physically inactive"),
        VocabularyWord(id: 265, word: "Uxorious", definition: "Having excessive devotion to one's wife"),
        VocabularyWord(id: 266, word: "Vituperative", definition: "Bitter and abusive"),
        VocabularyWord(id: 267, word: "Wraith", definition: "A ghost or ghostlike image"),
        VocabularyWord(id: 268, word: "Apotheosis", definition: "The highest point of development"),
        VocabularyWord(id: 269, word: "Bucolic", definition: "Relating to pleasant countryside"),
        VocabularyWord(id: 270, word: "Corroborate", definition: "To confirm or give support to"),
        VocabularyWord(id: 271, word: "Disseminate", definition: "To spread widely"),
        VocabularyWord(id: 272, word: "Epiphany", definition: "A sudden moment of revelation"),
        VocabularyWord(id: 273, word: "Fungible", definition: "Replaceable by another identical item"),
        VocabularyWord(id: 274, word: "Gambit", definition: "An opening remark or action"),
        VocabularyWord(id: 275, word: "Harbinger", definition: "A forerunner; a sign of things to come"),
        VocabularyWord(id: 276, word: "Impecunious", definition: "Having little or no money"),
        VocabularyWord(id: 277, word: "Jocose", definition: "Playful or humorous"),
        VocabularyWord(id: 278, word: "Lachrymose", definition: "Tearful or given to weeping"),
        VocabularyWord(id: 279, word: "Minatory", definition: "Expressing or conveying a threat"),
        VocabularyWord(id: 280, word: "Nugatory", definition: "Of no value or importance"),
        VocabularyWord(id: 281, word: "Onomatopoeia", definition: "Words that imitate sounds"),
        VocabularyWord(id: 282, word: "Panegyric", definition: "A public speech of praise"),
        VocabularyWord(id: 283, word: "Risible", definition: "Relating to laughter"),
        VocabularyWord(id: 284, word: "Serendipity", definition: "The occurrence of happy discoveries by chance"),
        VocabularyWord(id: 285, word: "Tenuous", definition: "Very weak or slight"),
        VocabularyWord(id: 286, word: "Ursine", definition: "Relating to or resembling bears"),
        VocabularyWord(id: 287, word: "Venial", definition: "Easily excused or forgiven"),
        VocabularyWord(id: 288, word: "Winnow", definition: "To reduce by removing the unwanted"),
        VocabularyWord(id: 289, word: "Assiduous", definition: "Showing great care and perseverance"),
        VocabularyWord(id: 290, word: "Blandishment", definition: "A flattering statement to persuade"),
        VocabularyWord(id: 291, word: "Calumny", definition: "A false and defamatory statement"),
        VocabularyWord(id: 292, word: "Decorum", definition: "Behavior in keeping with good taste"),
        VocabularyWord(id: 293, word: "Ennui", definition: "A feeling of listlessness and dissatisfaction"),
        VocabularyWord(id: 294, word: "Fraught", definition: "Filled with something undesirable"),
        VocabularyWord(id: 295, word: "Gossamer", definition: "A fine, filmy substance"),
        VocabularyWord(id: 296, word: "Hapless", definition: "Unfortunate"),
        VocabularyWord(id: 297, word: "Ignoble", definition: "Not honorable in character"),
        VocabularyWord(id: 298, word: "Jaundiced", definition: "Affected by bitterness or resentment"),
        VocabularyWord(id: 299, word: "Legerdemain", definition: "Skillful use of hands; trickery"),
        VocabularyWord(id: 300, word: "Malfeasance", definition: "Wrongdoing by a public official"),
        VocabularyWord(id: 301, word: "Nadir", definition: "The lowest point"),
        VocabularyWord(id: 302, word: "Obviate", definition: "To remove a difficulty"),
        VocabularyWord(id: 303, word: "Palaver", definition: "Lengthy and idle discussion"),
        VocabularyWord(id: 304, word: "Quagmire", definition: "A difficult situation"),
        VocabularyWord(id: 305, word: "Raffish", definition: "Unconventional but attractive"),
        VocabularyWord(id: 306, word: "Saturnine", definition: "Slow and gloomy"),
        VocabularyWord(id: 307, word: "Temerity", definition: "Excessive confidence or boldness"),
        VocabularyWord(id: 308, word: "Umbra", definition: "Shadow; shade"),
        VocabularyWord(id: 309, word: "Visceral", definition: "Relating to deep inward feelings"),
        VocabularyWord(id: 310, word: "Wry", definition: "Using dry, mocking humor"),
        VocabularyWord(id: 311, word: "Acrimonious", definition: "Angry and bitter"),
        VocabularyWord(id: 312, word: "Bromide", definition: "A trite and unoriginal statement"),
        VocabularyWord(id: 313, word: "Cloistered", definition: "Kept away from the outside world"),
        VocabularyWord(id: 314, word: "Diaphanous", definition: "Light, delicate, and translucent"),
        VocabularyWord(id: 315, word: "Egregious", definition: "Outstandingly bad; shocking"),
        VocabularyWord(id: 316, word: "Filibuster", definition: "Obstructing legislative progress"),
        VocabularyWord(id: 317, word: "Gauche", definition: "Lacking ease or grace; unsophisticated"),
        VocabularyWord(id: 318, word: "Heuristic", definition: "Enabling discovery or learning"),
        VocabularyWord(id: 319, word: "Inimical", definition: "Tending to obstruct or harm"),
        VocabularyWord(id: 320, word: "Jurisprudence", definition: "The theory or philosophy of law"),
        VocabularyWord(id: 321, word: "Kismet", definition: "Fate; destiny"),
        VocabularyWord(id: 322, word: "Lithe", definition: "Thin, supple, and graceful"),
        VocabularyWord(id: 323, word: "Munificent", definition: "Very generous"),
        VocabularyWord(id: 324, word: "Noisome", definition: "Having an unpleasant smell"),
        VocabularyWord(id: 325, word: "Obeisance", definition: "Deferential respect"),
        VocabularyWord(id: 326, word: "Perspicacious", definition: "Having a ready insight"),
        VocabularyWord(id: 327, word: "Quiescent", definition: "In a state of inactivity"),
        VocabularyWord(id: 328, word: "Redolent", definition: "Strongly reminiscent of"),
        VocabularyWord(id: 329, word: "Stolid", definition: "Calm and dependable"),
        VocabularyWord(id: 330, word: "Truculent", definition: "Eager to argue or fight"),
        VocabularyWord(id: 331, word: "Untoward", definition: "Unexpected and inappropriate"),
        VocabularyWord(id: 332, word: "Voluble", definition: "Speaking fluently and at length"),
        VocabularyWord(id: 333, word: "Wanton", definition: "Deliberate and unprovoked"),
        VocabularyWord(id: 334, word: "Abnegate", definition: "To renounce or reject"),
        VocabularyWord(id: 335, word: "Bilious", definition: "Spiteful; bad-tempered"),
        VocabularyWord(id: 336, word: "Churlish", definition: "Rude in a mean-spirited way"),
        VocabularyWord(id: 337, word: "Disingenuous", definition: "Not candid or sincere"),
        VocabularyWord(id: 338, word: "Enervate", definition: "To cause to feel drained"),
        VocabularyWord(id: 339, word: "Factitious", definition: "Artificially created"),
        VocabularyWord(id: 340, word: "Grandiloquent", definition: "Pompous in language"),
        VocabularyWord(id: 341, word: "Hauteur", definition: "Disdainful pride"),
        VocabularyWord(id: 342, word: "Inveterate", definition: "Having a habit long established"),
        VocabularyWord(id: 343, word: "Junta", definition: "A military group ruling a country"),
        VocabularyWord(id: 344, word: "Lassitude", definition: "Physical or mental weariness"),
        VocabularyWord(id: 345, word: "Mordant", definition: "Having a sharp quality"),
        VocabularyWord(id: 346, word: "Nescient", definition: "Lacking knowledge; ignorant"),
        VocabularyWord(id: 347, word: "Opprobrium", definition: "Harsh criticism or censure"),
        VocabularyWord(id: 348, word: "Penurious", definition: "Extremely poor"),
        VocabularyWord(id: 349, word: "Quotidian", definition: "Of or occurring every day"),
        VocabularyWord(id: 350, word: "Recumbent", definition: "Lying down"),
        VocabularyWord(id: 351, word: "Supercilious", definition: "Behaving as if superior"),
        VocabularyWord(id: 352, word: "Tendentious", definition: "Expressing a strong opinion"),
        VocabularyWord(id: 353, word: "Ululate", definition: "To howl or wail"),
        VocabularyWord(id: 354, word: "Variegated", definition: "Exhibiting different colors"),
        VocabularyWord(id: 355, word: "Winnow", definition: "To reduce to desirable elements"),
        VocabularyWord(id: 356, word: "Anachronism", definition: "Something belonging to another time"),
        VocabularyWord(id: 357, word: "Bloviate", definition: "To talk at length pompously"),
        VocabularyWord(id: 358, word: "Curmudgeon", definition: "A bad-tempered person"),
        VocabularyWord(id: 359, word: "Demagogue", definition: "A leader who exploits emotions"),
        VocabularyWord(id: 360, word: "Eschew", definition: "To deliberately avoid"),
        VocabularyWord(id: 361, word: "Filigree", definition: "Ornamental work of fine wire"),
        VocabularyWord(id: 362, word: "Gerrymander", definition: "To manipulate boundaries"),
        VocabularyWord(id: 363, word: "Hegemony", definition: "Leadership; dominance"),
        VocabularyWord(id: 364, word: "Interregnum", definition: "A period between regimes"),
    ]

    /// Returns the word for today based on the day of the year
    static func todaysWord() -> VocabularyWord {
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: Date()) ?? 1
        let index = (dayOfYear - 1) % words.count
        return words[index]
    }

    /// Returns the word for a specific date
    static func wordForDate(_ date: Date) -> VocabularyWord {
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: date) ?? 1
        let index = (dayOfYear - 1) % words.count
        return words[index]
    }
}
