//
//  VocabularyData.swift
//  vocab-builder
//
//  Created by Michael Zhao on 1/16/26.
//

import Foundation

enum PartOfSpeech: String, Codable {
    case noun = "noun"
    case verb = "verb"
    case adjective = "adj."
    case adverb = "adv."
    case phrase = "phrase"
}

struct VocabularyWord: Codable, Identifiable {
    let id: Int
    let word: String
    let definition: String
    let partOfSpeech: PartOfSpeech
    let example: String
}

struct VocabularyData {
    static let words: [VocabularyWord] = [
        VocabularyWord(id: 0, word: "Epistemic", definition: "Relating to knowledge or the conditions for acquiring it", partOfSpeech: .adjective, example: "The epistemic foundations of science rest on empirical evidence."),
        VocabularyWord(id: 1, word: "Liminal", definition: "Occupying a position at a threshold between two states", partOfSpeech: .adjective, example: "Adolescence is a liminal period between childhood and adulthood."),
        VocabularyWord(id: 2, word: "Shibboleth", definition: "A custom or belief that distinguishes a particular group", partOfSpeech: .noun, example: "Using jargon became a shibboleth that separated insiders from outsiders."),
        VocabularyWord(id: 3, word: "Palimpsest", definition: "Something reused but bearing traces of its earlier form", partOfSpeech: .noun, example: "The city is a palimpsest of architectural styles from different eras."),
        VocabularyWord(id: 4, word: "Ineluctable", definition: "Unable to be resisted or avoided; inevitable", partOfSpeech: .adjective, example: "The ineluctable march of time affects us all."),
        VocabularyWord(id: 5, word: "Synecdoche", definition: "A part used to represent the whole, or vice versa", partOfSpeech: .noun, example: "Saying 'all hands on deck' uses synecdoche, with hands representing sailors."),
        VocabularyWord(id: 6, word: "Apophenia", definition: "Perceiving meaningful connections between unrelated things", partOfSpeech: .noun, example: "Seeing faces in clouds is a common example of apophenia."),
        VocabularyWord(id: 7, word: "Proleptic", definition: "Anticipating and answering objections in advance", partOfSpeech: .adjective, example: "Her proleptic argument addressed counterpoints before they arose."),
        VocabularyWord(id: 8, word: "Cathexis", definition: "The concentration of mental energy on a person or idea", partOfSpeech: .noun, example: "His cathexis on his work left little energy for relationships."),
        VocabularyWord(id: 9, word: "Hermeneutic", definition: "Concerning interpretation, especially of texts or meaning", partOfSpeech: .adjective, example: "The hermeneutic approach to literature emphasizes reader interpretation."),
        VocabularyWord(id: 10, word: "Simulacrum", definition: "An image or representation of something; an unsatisfying imitation", partOfSpeech: .noun, example: "The theme park was a simulacrum of a European village."),
        VocabularyWord(id: 11, word: "Praxis", definition: "The practical application of theory or belief", partOfSpeech: .noun, example: "Good teaching requires both theory and praxis."),
        VocabularyWord(id: 12, word: "Teleological", definition: "Explaining phenomena by their purpose rather than cause", partOfSpeech: .adjective, example: "A teleological argument suggests design implies a designer."),
        VocabularyWord(id: 13, word: "Etiolated", definition: "Made weak or pale through lack of light or vitality", partOfSpeech: .adjective, example: "The etiolated plants had been kept too long in the dark basement."),
        VocabularyWord(id: 14, word: "Aporia", definition: "An irresolvable internal contradiction in a text or argument", partOfSpeech: .noun, example: "The philosopher's aporia left students questioning basic assumptions."),
        VocabularyWord(id: 15, word: "Interstitial", definition: "Relating to or occupying small spaces between things", partOfSpeech: .adjective, example: "Interstitial ads appear between content pages on the website."),
        VocabularyWord(id: 16, word: "Sui generis", definition: "Unique; in a class of its own", partOfSpeech: .phrase, example: "Her artistic style is sui generis, impossible to categorize."),
        VocabularyWord(id: 17, word: "Sclerotic", definition: "Becoming rigid and resistant to change", partOfSpeech: .adjective, example: "The sclerotic bureaucracy could not adapt to new challenges."),
        VocabularyWord(id: 18, word: "Anodyne", definition: "Unlikely to cause offense; blandly agreeable", partOfSpeech: .adjective, example: "The politician gave an anodyne speech that offended no one."),
        VocabularyWord(id: 19, word: "Propinquity", definition: "Nearness in place, time, or relationship", partOfSpeech: .noun, example: "Their propinquity in the office led to a close friendship."),
        VocabularyWord(id: 20, word: "Concatenate", definition: "To link together in a series or chain", partOfSpeech: .verb, example: "The program will concatenate all the text files into one document."),
        VocabularyWord(id: 21, word: "Peripatetic", definition: "Traveling from place to place, especially for work", partOfSpeech: .adjective, example: "The peripatetic consultant visited three cities each week."),
        VocabularyWord(id: 22, word: "Solipsistic", definition: "Self-absorbed; believing only one's own mind is certain", partOfSpeech: .adjective, example: "His solipsistic worldview made collaboration difficult."),
        VocabularyWord(id: 23, word: "Atavistic", definition: "Reverting to something ancient or ancestral", partOfSpeech: .adjective, example: "The atavistic urge to hunt remains in human psychology."),
        VocabularyWord(id: 24, word: "Chiasmus", definition: "A rhetorical reversal of word order for effect", partOfSpeech: .noun, example: "'Ask not what your country can do for you' is a famous chiasmus."),
        VocabularyWord(id: 25, word: "Entropic", definition: "Tending toward disorder or decline", partOfSpeech: .adjective, example: "Without maintenance, the garden fell into entropic decay."),
        VocabularyWord(id: 26, word: "Adumbrate", definition: "To outline or foreshadow; to partially disclose", partOfSpeech: .verb, example: "The opening chapter adumbrates the themes explored later."),
        VocabularyWord(id: 27, word: "Syncretic", definition: "Combining different beliefs, cultures, or schools of thought", partOfSpeech: .adjective, example: "The syncretic religion blended elements from multiple traditions."),
        VocabularyWord(id: 28, word: "Tendentious", definition: "Promoting a particular cause or viewpoint", partOfSpeech: .adjective, example: "The tendentious documentary presented only one side of the debate."),
        VocabularyWord(id: 29, word: "Lacuna", definition: "A gap or missing portion, especially in a text", partOfSpeech: .noun, example: "There is a significant lacuna in the historical record from that period."),
        VocabularyWord(id: 30, word: "Reify", definition: "To treat an abstraction as if it were concrete or real", partOfSpeech: .verb, example: "We should not reify concepts like 'the economy' as if they have agency."),
        VocabularyWord(id: 31, word: "Palliative", definition: "Relieving symptoms without addressing the cause", partOfSpeech: .adjective, example: "The treatment was merely palliative, not curative."),
        VocabularyWord(id: 32, word: "Axiomatic", definition: "Self-evidently true; unquestioned", partOfSpeech: .adjective, example: "It is axiomatic that all humans need water to survive."),
        VocabularyWord(id: 33, word: "Heterodox", definition: "Not conforming to accepted standards or beliefs", partOfSpeech: .adjective, example: "Her heterodox views challenged the established theory."),
        VocabularyWord(id: 34, word: "Apodictic", definition: "Clearly established; beyond dispute", partOfSpeech: .adjective, example: "Mathematical proofs aim to be apodictic in their certainty."),
        VocabularyWord(id: 35, word: "Putative", definition: "Generally considered or reputed to be", partOfSpeech: .adjective, example: "The putative author of the manuscript remains unknown."),
        VocabularyWord(id: 36, word: "Instantiate", definition: "To represent as a concrete example", partOfSpeech: .verb, example: "This case instantiates the broader pattern we've observed."),
        VocabularyWord(id: 37, word: "Metonymic", definition: "Using an attribute to stand for the thing itself", partOfSpeech: .adjective, example: "Calling executives 'suits' is a metonymic expression."),
        VocabularyWord(id: 38, word: "Aporetic", definition: "Relating to a state of puzzlement or doubt", partOfSpeech: .adjective, example: "The aporetic nature of the question left us without answers."),
        VocabularyWord(id: 39, word: "Procrustean", definition: "Enforcing conformity through arbitrary methods", partOfSpeech: .adjective, example: "The procrustean policy forced all students into the same mold."),
        VocabularyWord(id: 40, word: "Specious", definition: "Superficially plausible but actually wrong", partOfSpeech: .adjective, example: "His specious argument sounded convincing but fell apart under scrutiny."),
        VocabularyWord(id: 41, word: "Valence", definition: "The capacity of something to interact or influence", partOfSpeech: .noun, example: "The emotional valence of the message affected how it was received."),
        VocabularyWord(id: 42, word: "Aegis", definition: "Protection, sponsorship, or guidance", partOfSpeech: .noun, example: "The research was conducted under the aegis of the university."),
        VocabularyWord(id: 43, word: "Antediluvian", definition: "Extremely old-fashioned or out of date", partOfSpeech: .adjective, example: "His antediluvian views on technology made him resist computers."),
        VocabularyWord(id: 44, word: "Capacious", definition: "Having much space; roomy and accommodating", partOfSpeech: .adjective, example: "The capacious bag held all her travel essentials."),
        VocabularyWord(id: 45, word: "Desuetude", definition: "A state of disuse or inactivity", partOfSpeech: .noun, example: "The old law had fallen into desuetude decades ago."),
        VocabularyWord(id: 46, word: "Exigent", definition: "Pressing; demanding immediate attention", partOfSpeech: .adjective, example: "The exigent circumstances required an immediate response."),
        VocabularyWord(id: 47, word: "Fungible", definition: "Interchangeable; able to be substituted", partOfSpeech: .adjective, example: "Unlike art, currency is fungible—one dollar equals another."),
        VocabularyWord(id: 48, word: "Gestalt", definition: "A unified whole perceived as more than its parts", partOfSpeech: .noun, example: "The gestalt of the painting conveyed more than its individual elements."),
        VocabularyWord(id: 49, word: "Hortatory", definition: "Strongly encouraging or urging action", partOfSpeech: .adjective, example: "The coach's hortatory speech motivated the team before the game."),
        VocabularyWord(id: 50, word: "Imprimatur", definition: "Official approval or sanction", partOfSpeech: .noun, example: "The plan received the imprimatur of the board of directors."),
        VocabularyWord(id: 51, word: "Jeremiad", definition: "A prolonged lamentation or tale of woe", partOfSpeech: .noun, example: "His letter was a jeremiad about the state of modern society."),
        VocabularyWord(id: 52, word: "Kenosis", definition: "The emptying of one's will to become receptive", partOfSpeech: .noun, example: "Meditation involves a kenosis of worldly concerns."),
        VocabularyWord(id: 53, word: "Latent", definition: "Present but not visible or active; dormant", partOfSpeech: .adjective, example: "Her latent talent for music emerged in her twenties."),
        VocabularyWord(id: 54, word: "Miasma", definition: "An oppressive atmosphere of gloom or corruption", partOfSpeech: .noun, example: "A miasma of fear hung over the organization after the scandal."),
        VocabularyWord(id: 55, word: "Normative", definition: "Establishing or relating to a standard", partOfSpeech: .adjective, example: "Ethics is a normative discipline that prescribes how we should act."),
        VocabularyWord(id: 56, word: "Ossified", definition: "Rigid and resistant to change", partOfSpeech: .adjective, example: "The ossified traditions prevented any innovation."),
        VocabularyWord(id: 57, word: "Paradigmatic", definition: "Serving as a typical example or model", partOfSpeech: .adjective, example: "Her career is paradigmatic of success through persistence."),
        VocabularyWord(id: 58, word: "Quorum", definition: "The minimum number needed for valid proceedings", partOfSpeech: .noun, example: "Without a quorum, the committee could not vote on the proposal."),
        VocabularyWord(id: 59, word: "Redact", definition: "To edit for publication; to obscure sensitive content", partOfSpeech: .verb, example: "The agency redacted the classified portions of the document."),
        VocabularyWord(id: 60, word: "Seminal", definition: "Strongly influencing later developments", partOfSpeech: .adjective, example: "Darwin's seminal work changed the course of biology."),
        VocabularyWord(id: 61, word: "Tautological", definition: "Needlessly repetitive; true by definition", partOfSpeech: .adjective, example: "Saying 'free gift' is tautological since gifts are inherently free."),
        VocabularyWord(id: 62, word: "Ulterior", definition: "Beyond what is stated; hidden", partOfSpeech: .adjective, example: "She suspected he had ulterior motives for his generosity."),
        VocabularyWord(id: 63, word: "Venal", definition: "Susceptible to bribery; corrupt", partOfSpeech: .adjective, example: "The venal official accepted bribes to approve permits."),
        VocabularyWord(id: 64, word: "Watershed", definition: "A turning point; a critical dividing event", partOfSpeech: .noun, example: "The invention of the internet was a watershed moment in history."),
        VocabularyWord(id: 65, word: "Apothegm", definition: "A concise saying expressing a general truth", partOfSpeech: .noun, example: "'Less is more' is an apothegm often applied to design."),
        VocabularyWord(id: 66, word: "Bête noire", definition: "A person or thing particularly disliked or avoided", partOfSpeech: .noun, example: "Public speaking was her bête noire throughout her career."),
        VocabularyWord(id: 67, word: "Ceteris paribus", definition: "With all other things being equal", partOfSpeech: .phrase, example: "Ceteris paribus, lower prices increase demand."),
        VocabularyWord(id: 68, word: "Draconian", definition: "Excessively harsh or severe", partOfSpeech: .adjective, example: "The draconian penalties seemed disproportionate to the offense."),
        VocabularyWord(id: 69, word: "Endemic", definition: "Native to or characteristic of a particular place", partOfSpeech: .adjective, example: "Corruption was endemic in the failing institution."),
        VocabularyWord(id: 70, word: "Fait accompli", definition: "A thing already done and beyond reversal", partOfSpeech: .noun, example: "By announcing the decision publicly, she made it a fait accompli."),
        VocabularyWord(id: 71, word: "Gravamen", definition: "The essence or most serious part of a complaint", partOfSpeech: .noun, example: "The gravamen of the lawsuit was breach of contract."),
        VocabularyWord(id: 72, word: "Hegemonic", definition: "Having dominant influence over others", partOfSpeech: .adjective, example: "The hegemonic power shaped regional politics for decades."),
        VocabularyWord(id: 73, word: "Incipient", definition: "Beginning to develop; in an early stage", partOfSpeech: .adjective, example: "The incipient signs of recovery were encouraging."),
        VocabularyWord(id: 74, word: "Juggernaut", definition: "A massive, unstoppable force", partOfSpeech: .noun, example: "The tech company became a juggernaut in the industry."),
        VocabularyWord(id: 75, word: "Kinetic", definition: "Relating to or produced by motion", partOfSpeech: .adjective, example: "The kinetic energy of the falling object was converted to heat."),
        VocabularyWord(id: 76, word: "Lumpen", definition: "Unthinking; relating to displaced masses", partOfSpeech: .adjective, example: "The lumpen masses were easily swayed by propaganda."),
        VocabularyWord(id: 77, word: "Meretricious", definition: "Apparently attractive but lacking real value", partOfSpeech: .adjective, example: "The meretricious design impressed at first but soon disappointed."),
        VocabularyWord(id: 78, word: "Nascent", definition: "Just beginning to develop", partOfSpeech: .adjective, example: "The nascent startup showed tremendous potential."),
        VocabularyWord(id: 79, word: "Opprobrium", definition: "Harsh criticism or public disgrace", partOfSpeech: .noun, example: "He faced opprobrium for his unethical behavior."),
        VocabularyWord(id: 80, word: "Pari passu", definition: "At an equal rate or pace; side by side", partOfSpeech: .phrase, example: "The two investments grew pari passu over the decade."),
        VocabularyWord(id: 81, word: "Querulous", definition: "Habitually complaining; petulant", partOfSpeech: .adjective, example: "The querulous customer complained about everything."),
        VocabularyWord(id: 82, word: "Redound", definition: "To contribute greatly; to return as consequence", partOfSpeech: .verb, example: "Her hard work will redound to her benefit eventually."),
        VocabularyWord(id: 83, word: "Salient", definition: "Most noticeable or important", partOfSpeech: .adjective, example: "The salient points of the argument were summarized briefly."),
        VocabularyWord(id: 84, word: "Taxonomy", definition: "A scheme of classification", partOfSpeech: .noun, example: "Biologists use taxonomy to organize species into groups."),
        VocabularyWord(id: 85, word: "Umbra", definition: "A shadow; a region of complete darkness", partOfSpeech: .noun, example: "The moon passed through Earth's umbra during the eclipse."),
        VocabularyWord(id: 86, word: "Vitiate", definition: "To impair the quality or reduce the value of", partOfSpeech: .verb, example: "The procedural error vitiated the entire agreement."),
        VocabularyWord(id: 87, word: "Writ large", definition: "In a larger or more obvious form", partOfSpeech: .phrase, example: "The conflict was local politics writ large on the national stage."),
        VocabularyWord(id: 88, word: "Abrogate", definition: "To abolish or annul by authority", partOfSpeech: .verb, example: "The government moved to abrogate the outdated treaty."),
        VocabularyWord(id: 89, word: "Bellwether", definition: "An indicator of future trends", partOfSpeech: .noun, example: "This district is considered a bellwether for national elections."),
        VocabularyWord(id: 90, word: "Circuitous", definition: "Taking a roundabout route; not direct", partOfSpeech: .adjective, example: "We took a circuitous path to avoid the traffic."),
        VocabularyWord(id: 91, word: "Desiccated", definition: "Dried out; lacking vitality", partOfSpeech: .adjective, example: "The desiccated fruit had lost all its moisture."),
        VocabularyWord(id: 92, word: "Effete", definition: "No longer effective; exhausted of vitality", partOfSpeech: .adjective, example: "The effete aristocracy clung to fading traditions."),
        VocabularyWord(id: 93, word: "Fecund", definition: "Producing many ideas or offspring; fertile", partOfSpeech: .adjective, example: "The fecund author published three novels in one year."),
        VocabularyWord(id: 94, word: "Gambit", definition: "An opening move; a calculated risk", partOfSpeech: .noun, example: "Her opening gambit in negotiations was aggressive."),
        VocabularyWord(id: 95, word: "Hermetic", definition: "Completely sealed; protected from outside influence", partOfSpeech: .adjective, example: "The hermetic seal kept the contents fresh for years."),
        VocabularyWord(id: 96, word: "Invidious", definition: "Likely to cause resentment; unfairly discriminating", partOfSpeech: .adjective, example: "Making invidious comparisons between siblings causes harm."),
        VocabularyWord(id: 97, word: "Jettison", definition: "To abandon or discard", partOfSpeech: .verb, example: "They had to jettison unnecessary cargo to stay afloat."),
        VocabularyWord(id: 98, word: "Kismet", definition: "Fate; destiny", partOfSpeech: .noun, example: "Meeting her there seemed like kismet."),
        VocabularyWord(id: 99, word: "Legerdemain", definition: "Skillful deception; sleight of hand", partOfSpeech: .noun, example: "The magician's legerdemain amazed the audience."),
        VocabularyWord(id: 100, word: "Malfeasance", definition: "Wrongdoing, especially by a public official", partOfSpeech: .noun, example: "The mayor was investigated for financial malfeasance."),
        VocabularyWord(id: 101, word: "Nadir", definition: "The lowest point", partOfSpeech: .noun, example: "The company reached its nadir before the turnaround."),
        VocabularyWord(id: 102, word: "Obviate", definition: "To remove or prevent a difficulty", partOfSpeech: .verb, example: "The new system will obviate the need for manual entry."),
        VocabularyWord(id: 103, word: "Paradigm", definition: "A typical example or pattern of something", partOfSpeech: .noun, example: "The discovery created a new paradigm in physics."),
        VocabularyWord(id: 104, word: "Quintessential", definition: "Representing the most perfect example", partOfSpeech: .adjective, example: "She is the quintessential professional in her field."),
        VocabularyWord(id: 105, word: "Recalcitrant", definition: "Stubbornly resistant to authority", partOfSpeech: .adjective, example: "The recalcitrant child refused to follow instructions."),
        VocabularyWord(id: 106, word: "Stolid", definition: "Calm, dependable, and showing little emotion", partOfSpeech: .adjective, example: "His stolid demeanor hid his inner turmoil."),
        VocabularyWord(id: 107, word: "Trenchant", definition: "Vigorous, effective, and articulate", partOfSpeech: .adjective, example: "Her trenchant critique exposed the flaws in the plan."),
        VocabularyWord(id: 108, word: "Utilitarian", definition: "Designed for usefulness rather than beauty", partOfSpeech: .adjective, example: "The utilitarian design prioritized function over form."),
        VocabularyWord(id: 109, word: "Vexed", definition: "Much debated; annoyed", partOfSpeech: .adjective, example: "The vexed question has no easy answer."),
        VocabularyWord(id: 110, word: "Zeitgeist", definition: "The defining spirit of a particular period", partOfSpeech: .noun, example: "The film captured the zeitgeist of the era perfectly."),
        VocabularyWord(id: 111, word: "Allocution", definition: "A formal speech, especially a warning or exhortation", partOfSpeech: .noun, example: "The judge delivered an allocution before sentencing."),
        VocabularyWord(id: 112, word: "Bowdlerize", definition: "To remove content considered offensive", partOfSpeech: .verb, example: "The publisher bowdlerized the classic novel for children."),
        VocabularyWord(id: 113, word: "Cabalistic", definition: "Having a secret or esoteric meaning", partOfSpeech: .adjective, example: "The cabalistic symbols puzzled outsiders."),
        VocabularyWord(id: 114, word: "Demotic", definition: "Relating to ordinary people; vernacular", partOfSpeech: .adjective, example: "The writer used demotic language to reach a wider audience."),
        VocabularyWord(id: 115, word: "Effluvium", definition: "An unpleasant or harmful odor or discharge", partOfSpeech: .noun, example: "An effluvium of chemicals hung over the factory town."),
        VocabularyWord(id: 116, word: "Fissiparous", definition: "Inclined to cause division or fragment", partOfSpeech: .adjective, example: "Fissiparous tendencies threatened to split the organization."),
        VocabularyWord(id: 117, word: "Gravid", definition: "Full of meaning; pregnant with significance", partOfSpeech: .adjective, example: "The moment was gravid with possibilities."),
        VocabularyWord(id: 118, word: "Heuristic", definition: "Enabling discovery through experimentation", partOfSpeech: .adjective, example: "The heuristic method encourages learning by doing."),
        VocabularyWord(id: 119, word: "Immanent", definition: "Existing or operating within; inherent", partOfSpeech: .adjective, example: "Justice is immanent in the structure of society."),
        VocabularyWord(id: 120, word: "Juxtapose", definition: "To place side by side for comparison or contrast", partOfSpeech: .verb, example: "The artist juxtaposed old and new styles in her work."),
        VocabularyWord(id: 121, word: "Kludge", definition: "An awkward but effective solution to a problem", partOfSpeech: .noun, example: "The fix was a kludge, but it kept the system running."),
        VocabularyWord(id: 122, word: "Lucubration", definition: "Laborious study or meditation", partOfSpeech: .noun, example: "His lucubration on the subject filled several volumes."),
        VocabularyWord(id: 123, word: "Malapropism", definition: "Mistaken use of a word for a similar-sounding one", partOfSpeech: .noun, example: "Saying 'for all intensive purposes' is a common malapropism."),
        VocabularyWord(id: 124, word: "Nostrum", definition: "A pet scheme; a questionable remedy", partOfSpeech: .noun, example: "Tax cuts are often proposed as a nostrum for economic woes."),
        VocabularyWord(id: 125, word: "Otiose", definition: "Serving no practical purpose; idle", partOfSpeech: .adjective, example: "The otiose regulations only added bureaucratic burden."),
        VocabularyWord(id: 126, word: "Persiflage", definition: "Light, mocking banter", partOfSpeech: .noun, example: "The dinner conversation was full of witty persiflage."),
        VocabularyWord(id: 127, word: "Quotidian", definition: "Ordinary; everyday", partOfSpeech: .adjective, example: "She found beauty in quotidian moments of life."),
        VocabularyWord(id: 128, word: "Rapprochement", definition: "The establishment of cordial relations", partOfSpeech: .noun, example: "The treaty marked a rapprochement between former enemies."),
        VocabularyWord(id: 129, word: "Sartorial", definition: "Relating to tailoring or clothing style", partOfSpeech: .adjective, example: "His sartorial choices were always impeccable."),
        VocabularyWord(id: 130, word: "Tendentious", definition: "Expressing a strongly biased point of view", partOfSpeech: .adjective, example: "The tendentious article ignored contrary evidence."),
        VocabularyWord(id: 131, word: "Unctuous", definition: "Excessively flattering; oily", partOfSpeech: .adjective, example: "His unctuous manner made her uncomfortable."),
        VocabularyWord(id: 132, word: "Vicissitude", definition: "A change of circumstances, typically unwelcome", partOfSpeech: .noun, example: "The vicissitudes of life taught her resilience."),
        VocabularyWord(id: 133, word: "Weltanschauung", definition: "A comprehensive worldview or philosophy", partOfSpeech: .noun, example: "His weltanschauung shaped all his political views."),
        VocabularyWord(id: 134, word: "Ameliorate", definition: "To make something bad better", partOfSpeech: .verb, example: "The new policy aimed to ameliorate working conditions."),
        VocabularyWord(id: 135, word: "Bildungsroman", definition: "A novel about a person's formative years", partOfSpeech: .noun, example: "Great Expectations is a classic bildungsroman."),
        VocabularyWord(id: 136, word: "Calumny", definition: "A false statement damaging to reputation", partOfSpeech: .noun, example: "The calumny spread by rivals ruined his career."),
        VocabularyWord(id: 137, word: "Desideratum", definition: "Something considered necessary or desired", partOfSpeech: .noun, example: "Clarity is a desideratum in legal writing."),
        VocabularyWord(id: 138, word: "Emollient", definition: "Having a softening or soothing effect", partOfSpeech: .adjective, example: "Her emollient words calmed the tense situation."),
        VocabularyWord(id: 139, word: "Flâneur", definition: "One who strolls and observes society", partOfSpeech: .noun, example: "The flâneur wandered the city streets, watching life unfold."),
        VocabularyWord(id: 140, word: "Granular", definition: "Consisting of fine details; highly specific", partOfSpeech: .adjective, example: "We need a more granular analysis of the data."),
        VocabularyWord(id: 141, word: "Homologous", definition: "Having the same relation or structure", partOfSpeech: .adjective, example: "The human arm and whale flipper are homologous structures."),
        VocabularyWord(id: 142, word: "Impugn", definition: "To dispute the truth or validity of", partOfSpeech: .verb, example: "The lawyer attempted to impugn the witness's credibility."),
        VocabularyWord(id: 143, word: "Jocund", definition: "Cheerful and lighthearted", partOfSpeech: .adjective, example: "The jocund atmosphere at the party was infectious."),
        VocabularyWord(id: 144, word: "Kinesthesia", definition: "Awareness of body position and movement", partOfSpeech: .noun, example: "Dancers develop exceptional kinesthesia through training."),
        VocabularyWord(id: 145, word: "Laudatory", definition: "Expressing praise", partOfSpeech: .adjective, example: "The laudatory review boosted book sales significantly."),
        VocabularyWord(id: 146, word: "Morphology", definition: "The study of forms and structures", partOfSpeech: .noun, example: "Linguistics includes the morphology of word formation."),
        VocabularyWord(id: 147, word: "Neologism", definition: "A newly coined word or expression", partOfSpeech: .noun, example: "'Selfie' was once a neologism but is now common."),
        VocabularyWord(id: 148, word: "Ontological", definition: "Relating to the nature of being or existence", partOfSpeech: .adjective, example: "The ontological argument attempts to prove God's existence."),
        VocabularyWord(id: 149, word: "Propitious", definition: "Indicating a favorable outcome", partOfSpeech: .adjective, example: "The propitious weather made for a perfect wedding day."),
        VocabularyWord(id: 150, word: "Quiddity", definition: "The essential nature of something", partOfSpeech: .noun, example: "The quiddity of her argument eluded most listeners."),
        VocabularyWord(id: 151, word: "Recondite", definition: "Obscure; known only to a few", partOfSpeech: .adjective, example: "The recondite subject required years of study to master."),
        VocabularyWord(id: 152, word: "Solecism", definition: "A grammatical mistake or breach of etiquette", partOfSpeech: .noun, example: "Using 'irregardless' is considered a solecism by grammarians."),
        VocabularyWord(id: 153, word: "Tergiversate", definition: "To change repeatedly one's attitude or opinions", partOfSpeech: .verb, example: "Politicians who tergiversate lose voter trust."),
        VocabularyWord(id: 154, word: "Usufruct", definition: "The right to use another's property", partOfSpeech: .noun, example: "She held usufruct over the estate during her lifetime."),
        VocabularyWord(id: 155, word: "Verisimilitude", definition: "The appearance of being true or real", partOfSpeech: .noun, example: "The novel achieved verisimilitude through detailed research."),
        VocabularyWord(id: 156, word: "Whilom", definition: "Former; erstwhile", partOfSpeech: .adjective, example: "The whilom champion returned for one last fight."),
        VocabularyWord(id: 157, word: "Abnegate", definition: "To renounce or reject", partOfSpeech: .verb, example: "He chose to abnegate his inheritance for moral reasons."),
        VocabularyWord(id: 158, word: "Brio", definition: "Vigor and vivacity", partOfSpeech: .noun, example: "She performed the piece with remarkable brio."),
        VocabularyWord(id: 159, word: "Canard", definition: "An unfounded rumor or story", partOfSpeech: .noun, example: "The story about his resignation was just a canard."),
        VocabularyWord(id: 160, word: "Détente", definition: "The easing of hostility between countries", partOfSpeech: .noun, example: "The summit marked a period of détente between the nations."),
        VocabularyWord(id: 161, word: "Ersatz", definition: "An inferior substitute", partOfSpeech: .adjective, example: "The ersatz coffee tasted nothing like the real thing."),
        VocabularyWord(id: 162, word: "Fractious", definition: "Irritable and quarrelsome", partOfSpeech: .adjective, example: "The fractious committee could not reach agreement."),
        VocabularyWord(id: 163, word: "Galvanic", definition: "Sudden and dramatic; stimulating", partOfSpeech: .adjective, example: "The news had a galvanic effect on the stock market."),
        VocabularyWord(id: 164, word: "Hieratic", definition: "Of or concerning priests; formal and stylized", partOfSpeech: .adjective, example: "The hieratic poses in Egyptian art were highly symbolic."),
        VocabularyWord(id: 165, word: "Inchoate", definition: "Just begun; not fully formed", partOfSpeech: .adjective, example: "The plan was still inchoate and needed development."),
        VocabularyWord(id: 166, word: "Jejune", definition: "Naive; lacking substance or interest", partOfSpeech: .adjective, example: "The jejune commentary added nothing to the discussion."),
        VocabularyWord(id: 167, word: "Kyriarchy", definition: "A social system built on intersecting oppressions", partOfSpeech: .noun, example: "Scholars use kyriarchy to analyze overlapping power structures."),
        VocabularyWord(id: 168, word: "Limpid", definition: "Clear and transparent; easily understood", partOfSpeech: .adjective, example: "Her limpid prose made complex ideas accessible."),
        VocabularyWord(id: 169, word: "Mandarin", definition: "A powerful official; an influential intellectual", partOfSpeech: .noun, example: "The mandarins of the literary world praised the novel."),
        VocabularyWord(id: 170, word: "Numinous", definition: "Having a strong spiritual or religious quality", partOfSpeech: .adjective, example: "The ancient temple had a numinous atmosphere."),
        VocabularyWord(id: 171, word: "Oppugn", definition: "To call into question; to oppose", partOfSpeech: .verb, example: "Critics oppugned the validity of the research findings."),
        VocabularyWord(id: 172, word: "Prescient", definition: "Having knowledge of events before they occur", partOfSpeech: .adjective, example: "Her prescient warning about the market crash proved accurate."),
        VocabularyWord(id: 173, word: "Quondam", definition: "Former", partOfSpeech: .adjective, example: "He met his quondam colleague at the reunion."),
        VocabularyWord(id: 174, word: "Recusant", definition: "Refusing to submit to authority", partOfSpeech: .adjective, example: "The recusant members voted against the party line."),
        VocabularyWord(id: 175, word: "Sanguine", definition: "Optimistic, especially in a difficult situation", partOfSpeech: .adjective, example: "Despite the setbacks, she remained sanguine about success."),
        VocabularyWord(id: 176, word: "Tertiary", definition: "Third in order or level", partOfSpeech: .adjective, example: "The tertiary stage of treatment addressed remaining issues."),
        VocabularyWord(id: 177, word: "Univocal", definition: "Having only one meaning; unambiguous", partOfSpeech: .adjective, example: "Legal documents aim to be univocal to avoid disputes."),
        VocabularyWord(id: 178, word: "Volte-face", definition: "A sudden reversal of opinion or position", partOfSpeech: .noun, example: "His volte-face on the policy surprised everyone."),
        VocabularyWord(id: 179, word: "Wunderkind", definition: "A young person who achieves great success", partOfSpeech: .noun, example: "The wunderkind graduated from college at sixteen."),
        VocabularyWord(id: 180, word: "Antinomy", definition: "A contradiction between two reasonable principles", partOfSpeech: .noun, example: "The antinomy between freedom and security is often debated."),
        VocabularyWord(id: 181, word: "Bromide", definition: "A trite, unoriginal statement", partOfSpeech: .noun, example: "'Time heals all wounds' is a bromide often shared."),
        VocabularyWord(id: 182, word: "Concatenation", definition: "A series of linked things or events", partOfSpeech: .noun, example: "A concatenation of errors led to the disaster."),
        VocabularyWord(id: 183, word: "Didactic", definition: "Intended to teach or instruct", partOfSpeech: .adjective, example: "The didactic novel taught moral lessons to readers."),
        VocabularyWord(id: 184, word: "Elide", definition: "To omit or merge sounds; to ignore", partOfSpeech: .verb, example: "Speakers often elide syllables in casual conversation."),
        VocabularyWord(id: 185, word: "Fugacious", definition: "Tending to disappear; fleeting", partOfSpeech: .adjective, example: "The fugacious beauty of cherry blossoms inspires poets."),
        VocabularyWord(id: 186, word: "Geist", definition: "The spirit of an individual or era", partOfSpeech: .noun, example: "The geist of the movement was captured in her art."),
        VocabularyWord(id: 187, word: "Heterogeneous", definition: "Diverse in character or content", partOfSpeech: .adjective, example: "The city has a heterogeneous population from many backgrounds."),
        VocabularyWord(id: 188, word: "Ineffable", definition: "Too great or extreme to be expressed in words", partOfSpeech: .adjective, example: "The ineffable beauty of the sunset left her speechless."),
        VocabularyWord(id: 189, word: "Juxtaposition", definition: "The fact of placing things close together for contrast", partOfSpeech: .noun, example: "The juxtaposition of old and new architecture was striking."),
        VocabularyWord(id: 190, word: "Kakistocracy", definition: "Government by the least qualified citizens", partOfSpeech: .noun, example: "Critics called the regime a kakistocracy of incompetents."),
        VocabularyWord(id: 191, word: "Laconic", definition: "Using very few words", partOfSpeech: .adjective, example: "His laconic reply gave nothing away about his feelings."),
        VocabularyWord(id: 192, word: "Martinet", definition: "A strict disciplinarian", partOfSpeech: .noun, example: "The martinet coach demanded perfection from every player."),
        VocabularyWord(id: 193, word: "Necromancy", definition: "Communication with the dead; sorcery", partOfSpeech: .noun, example: "The fantasy novel featured a villain skilled in necromancy."),
        VocabularyWord(id: 194, word: "Obsequy", definition: "A funeral rite", partOfSpeech: .noun, example: "The obsequies were held in accordance with tradition."),
        VocabularyWord(id: 195, word: "Perspicuous", definition: "Clearly expressed and easily understood", partOfSpeech: .adjective, example: "Her perspicuous explanation clarified the complex topic."),
        VocabularyWord(id: 196, word: "Quiescent", definition: "In a state of quiet inactivity", partOfSpeech: .adjective, example: "The volcano had been quiescent for centuries."),
        VocabularyWord(id: 197, word: "Realpolitik", definition: "Politics based on practical rather than moral aims", partOfSpeech: .noun, example: "The diplomat practiced realpolitik in negotiations."),
        VocabularyWord(id: 198, word: "Shibboleth", definition: "A belief or practice that distinguishes a group", partOfSpeech: .noun, example: "Technical jargon serves as a shibboleth among experts."),
        VocabularyWord(id: 199, word: "Truculent", definition: "Eager to argue or fight; aggressively defiant", partOfSpeech: .adjective, example: "The truculent negotiator refused to compromise."),
        VocabularyWord(id: 200, word: "Umbrageous", definition: "Easily offended; providing shade", partOfSpeech: .adjective, example: "His umbrageous nature made him difficult to work with."),
        VocabularyWord(id: 201, word: "Vouchsafe", definition: "To give or grant something in a condescending way", partOfSpeech: .verb, example: "He vouchsafed a rare smile to his subordinates."),
        VocabularyWord(id: 202, word: "Waylay", definition: "To stop and detain someone unexpectedly", partOfSpeech: .verb, example: "Reporters waylaid the celebrity outside the hotel."),
        VocabularyWord(id: 203, word: "Acephalous", definition: "Without a leader or head", partOfSpeech: .adjective, example: "The acephalous organization struggled to make decisions."),
        VocabularyWord(id: 204, word: "Belie", definition: "To fail to give a true impression of", partOfSpeech: .verb, example: "Her calm demeanor belied her inner anxiety."),
        VocabularyWord(id: 205, word: "Chicanery", definition: "Deception by clever legal maneuvering", partOfSpeech: .noun, example: "The contract was full of legal chicanery."),
        VocabularyWord(id: 206, word: "Denouement", definition: "The final resolution of a plot", partOfSpeech: .noun, example: "The denouement of the mystery surprised everyone."),
        VocabularyWord(id: 207, word: "Ebullience", definition: "The quality of being cheerful and full of energy", partOfSpeech: .noun, example: "Her ebullience was contagious at the celebration."),
        VocabularyWord(id: 208, word: "Febrile", definition: "Having or showing symptoms of fever; feverishly excited", partOfSpeech: .adjective, example: "The febrile atmosphere before the election was intense."),
        VocabularyWord(id: 209, word: "Gainsay", definition: "To deny or contradict", partOfSpeech: .verb, example: "No one could gainsay the evidence presented in court."),
        VocabularyWord(id: 210, word: "Hagiography", definition: "An idealized biography; excessive admiration", partOfSpeech: .noun, example: "The biography was more hagiography than honest account."),
        VocabularyWord(id: 211, word: "Imprimatur", definition: "Official approval or sanction", partOfSpeech: .noun, example: "The project received the CEO's imprimatur before launch."),
        VocabularyWord(id: 212, word: "Juvenilia", definition: "Works produced by an author in youth", partOfSpeech: .noun, example: "The exhibition featured the artist's juvenilia from childhood."),
        VocabularyWord(id: 213, word: "Kvetch", definition: "To complain persistently", partOfSpeech: .verb, example: "He would kvetch about the weather no matter what."),
        VocabularyWord(id: 214, word: "Leitmotif", definition: "A recurring theme in a work or a person's life", partOfSpeech: .noun, example: "Redemption is a leitmotif throughout her novels."),
        VocabularyWord(id: 215, word: "Maudlin", definition: "Self-pityingly sentimental", partOfSpeech: .adjective, example: "After a few drinks, he became maudlin about his past."),
        VocabularyWord(id: 216, word: "Nexus", definition: "A connection or series of connections", partOfSpeech: .noun, example: "The city serves as a nexus for international commerce."),
        VocabularyWord(id: 217, word: "Obloquy", definition: "Strong public criticism or verbal abuse", partOfSpeech: .noun, example: "The politician faced obloquy for his controversial remarks."),
        VocabularyWord(id: 218, word: "Paladin", definition: "A champion of a cause; a heroic advocate", partOfSpeech: .noun, example: "She became a paladin for environmental justice."),
        VocabularyWord(id: 219, word: "Quixotic", definition: "Exceedingly idealistic; unrealistic", partOfSpeech: .adjective, example: "His quixotic quest to reform the system was admirable."),
        VocabularyWord(id: 220, word: "Recidivist", definition: "One who repeatedly commits crimes or errors", partOfSpeech: .noun, example: "The recidivist returned to prison within a year."),
        VocabularyWord(id: 221, word: "Sacrosanct", definition: "Too important to be changed or interfered with", partOfSpeech: .adjective, example: "The family dinner tradition was sacrosanct."),
        VocabularyWord(id: 222, word: "Torpor", definition: "A state of physical or mental inactivity", partOfSpeech: .noun, example: "The summer heat induced a torpor in the afternoon."),
        VocabularyWord(id: 223, word: "Uxoricide", definition: "The killing of one's wife", partOfSpeech: .noun, example: "The detective investigated the suspected uxoricide."),
        VocabularyWord(id: 224, word: "Verbiage", definition: "Excessive or unnecessarily complex language", partOfSpeech: .noun, example: "Cut the verbiage and get to the point."),
        VocabularyWord(id: 225, word: "Whelm", definition: "To engulf or submerge completely", partOfSpeech: .verb, example: "Waves whelmed the small boat during the storm."),
        VocabularyWord(id: 226, word: "Antipodal", definition: "Relating to opposite sides; diametrically opposed", partOfSpeech: .adjective, example: "Their antipodal views made compromise difficult."),
        VocabularyWord(id: 227, word: "Bifurcate", definition: "To divide into two branches", partOfSpeech: .verb, example: "The river bifurcates just before the valley."),
        VocabularyWord(id: 228, word: "Comity", definition: "Mutual courtesy and consideration", partOfSpeech: .noun, example: "The nations maintained comity despite disagreements."),
        VocabularyWord(id: 229, word: "Dilatory", definition: "Slow to act; intended to cause delay", partOfSpeech: .adjective, example: "The dilatory tactics frustrated the opposing team."),
        VocabularyWord(id: 230, word: "Epicene", definition: "Having characteristics of both sexes; effeminate", partOfSpeech: .adjective, example: "The epicene beauty of the model challenged conventions."),
        VocabularyWord(id: 231, word: "Froideur", definition: "Coldness or aloofness in manner", partOfSpeech: .noun, example: "Her froideur kept colleagues at a distance."),
        VocabularyWord(id: 232, word: "Gnomic", definition: "Expressed in short, pithy sayings", partOfSpeech: .adjective, example: "The philosopher's gnomic utterances required interpretation."),
        VocabularyWord(id: 233, word: "Haptic", definition: "Relating to the sense of touch", partOfSpeech: .adjective, example: "Haptic feedback makes phone keyboards feel more real."),
        VocabularyWord(id: 234, word: "Inimical", definition: "Tending to obstruct or harm; hostile", partOfSpeech: .adjective, example: "The policy was inimical to small business growth."),
        VocabularyWord(id: 235, word: "Jocosity", definition: "The quality of being humorous", partOfSpeech: .noun, example: "His jocosity lightened the tense meeting."),
        VocabularyWord(id: 236, word: "Lachrymose", definition: "Given to weeping; tearful", partOfSpeech: .adjective, example: "The lachrymose farewell touched everyone present."),
        VocabularyWord(id: 237, word: "Meliorism", definition: "Belief that the world can be improved by human effort", partOfSpeech: .noun, example: "Her meliorism drove her activism for decades."),
        VocabularyWord(id: 238, word: "Nugatory", definition: "Of no value or importance", partOfSpeech: .adjective, example: "The objections were deemed nugatory and dismissed."),
        VocabularyWord(id: 239, word: "Orotund", definition: "Full and round in sound; pompous", partOfSpeech: .adjective, example: "The speaker's orotund style impressed some but bored others."),
        VocabularyWord(id: 240, word: "Palaver", definition: "Prolonged idle discussion", partOfSpeech: .noun, example: "The meeting devolved into endless palaver."),
        VocabularyWord(id: 241, word: "Qua", definition: "In the capacity of", partOfSpeech: .phrase, example: "He spoke qua expert, not as a friend."),
        VocabularyWord(id: 242, word: "Recrudescence", definition: "The revival of something unwelcome", partOfSpeech: .noun, example: "The recrudescence of old tensions worried diplomats."),
        VocabularyWord(id: 243, word: "Simulacrum", definition: "An unsatisfying imitation or substitute", partOfSpeech: .noun, example: "The reproduction was merely a simulacrum of the original."),
        VocabularyWord(id: 244, word: "Trope", definition: "A common or recurring theme or device", partOfSpeech: .noun, example: "The hero's journey is a trope in many stories."),
        VocabularyWord(id: 245, word: "Ukase", definition: "An arbitrary command", partOfSpeech: .noun, example: "The manager's ukase was met with silent resentment."),
        VocabularyWord(id: 246, word: "Velleity", definition: "A wish without accompanying action", partOfSpeech: .noun, example: "His desire to travel remained a mere velleity."),
        VocabularyWord(id: 247, word: "Wonted", definition: "Habitual; usual", partOfSpeech: .adjective, example: "She resumed her wonted routine after the vacation."),
        VocabularyWord(id: 248, word: "Apostate", definition: "One who abandons a belief or principle", partOfSpeech: .noun, example: "The apostate was shunned by former allies."),
        VocabularyWord(id: 249, word: "Bathetic", definition: "Producing an effect of anticlimax", partOfSpeech: .adjective, example: "The bathetic ending disappointed readers who expected more."),
        VocabularyWord(id: 250, word: "Callow", definition: "Inexperienced and immature", partOfSpeech: .adjective, example: "The callow youth learned hard lessons quickly."),
        VocabularyWord(id: 251, word: "Declivity", definition: "A downward slope", partOfSpeech: .noun, example: "The path followed the declivity down to the river."),
        VocabularyWord(id: 252, word: "Encomium", definition: "A speech or piece of writing that praises highly", partOfSpeech: .noun, example: "The obituary was an encomium to a life well lived."),
        VocabularyWord(id: 253, word: "Fulsome", definition: "Excessively flattering; abundant to excess", partOfSpeech: .adjective, example: "His fulsome praise seemed insincere."),
        VocabularyWord(id: 254, word: "Genuflect", definition: "To show deep respect; to kneel", partOfSpeech: .verb, example: "Visitors genuflected before the altar."),
        VocabularyWord(id: 255, word: "Hortatory", definition: "Strongly encouraging or urging", partOfSpeech: .adjective, example: "The hortatory speech rallied the troops."),
        VocabularyWord(id: 256, word: "Inimitable", definition: "Impossible to imitate; unique", partOfSpeech: .adjective, example: "Her inimitable style set her apart from competitors."),
        VocabularyWord(id: 257, word: "Jingoistic", definition: "Extremely patriotic; bellicose", partOfSpeech: .adjective, example: "The jingoistic rhetoric inflamed international tensions."),
        VocabularyWord(id: 258, word: "Kith", definition: "One's friends, acquaintances, and relations", partOfSpeech: .noun, example: "She celebrated the holiday with kith and kin."),
        VocabularyWord(id: 259, word: "Lassitude", definition: "Physical or mental weariness", partOfSpeech: .noun, example: "A general lassitude settled over the office on Friday."),
        VocabularyWord(id: 260, word: "Maunder", definition: "To talk or move aimlessly", partOfSpeech: .verb, example: "He maundered on without making any clear point."),
        VocabularyWord(id: 261, word: "Nescient", definition: "Lacking knowledge; ignorant", partOfSpeech: .adjective, example: "The nescient voter had no idea about the issues."),
        VocabularyWord(id: 262, word: "Obstreperous", definition: "Noisy and difficult to control", partOfSpeech: .adjective, example: "The obstreperous crowd disrupted the proceedings."),
        VocabularyWord(id: 263, word: "Pecuniary", definition: "Relating to money", partOfSpeech: .adjective, example: "The lawsuit sought pecuniary damages for the loss."),
        VocabularyWord(id: 264, word: "Quietus", definition: "Death or something that causes death; a final settlement", partOfSpeech: .noun, example: "The scandal put a quietus on his political ambitions."),
        VocabularyWord(id: 265, word: "Raffish", definition: "Unconventional and slightly disreputable but appealing", partOfSpeech: .adjective, example: "The raffish charm of the neighborhood attracted artists."),
        VocabularyWord(id: 266, word: "Saturnine", definition: "Gloomy; sluggish in temperament", partOfSpeech: .adjective, example: "His saturnine disposition made him poor company."),
        VocabularyWord(id: 267, word: "Tutelage", definition: "Protection or guardianship; instruction", partOfSpeech: .noun, example: "She flourished under the tutelage of the master craftsman."),
        VocabularyWord(id: 268, word: "Usury", definition: "Lending money at unreasonably high interest", partOfSpeech: .noun, example: "Laws against usury protect vulnerable borrowers."),
        VocabularyWord(id: 269, word: "Vagary", definition: "An unpredictable change; a whim", partOfSpeech: .noun, example: "The vagaries of weather affected the harvest."),
        VocabularyWord(id: 270, word: "Waspish", definition: "Readily irritated; sharply critical", partOfSpeech: .adjective, example: "Her waspish comments silenced the room."),
        VocabularyWord(id: 271, word: "Adjunct", definition: "An additional but not essential part", partOfSpeech: .noun, example: "The adjunct professor taught evening classes."),
        VocabularyWord(id: 272, word: "Benighted", definition: "Ignorant; in a state of intellectual darkness", partOfSpeech: .adjective, example: "The benighted policies reflected outdated thinking."),
        VocabularyWord(id: 273, word: "Cogent", definition: "Clear, logical, and convincing", partOfSpeech: .adjective, example: "She presented a cogent argument that swayed the jury."),
        VocabularyWord(id: 274, word: "Demur", definition: "To raise objections or show reluctance", partOfSpeech: .verb, example: "He demurred when asked to take on more work."),
        VocabularyWord(id: 275, word: "Equivocate", definition: "To use ambiguous language to deceive", partOfSpeech: .verb, example: "Politicians often equivocate to avoid direct answers."),
        VocabularyWord(id: 276, word: "Fiduciary", definition: "Involving trust, especially regarding money", partOfSpeech: .adjective, example: "The advisor has a fiduciary duty to her clients."),
        VocabularyWord(id: 277, word: "Gauche", definition: "Lacking social grace; tactless", partOfSpeech: .adjective, example: "His gauche comment embarrassed everyone at dinner."),
        VocabularyWord(id: 278, word: "Hegemony", definition: "Dominance by one group over others", partOfSpeech: .noun, example: "The empire maintained hegemony over the region for centuries."),
        VocabularyWord(id: 279, word: "Infelicitous", definition: "Unfortunate; inappropriate", partOfSpeech: .adjective, example: "His infelicitous choice of words caused offense."),
        VocabularyWord(id: 280, word: "Jargon", definition: "Special words used by a profession or group", partOfSpeech: .noun, example: "Technical jargon can alienate general audiences."),
        VocabularyWord(id: 281, word: "Kowtow", definition: "To act in a submissive manner", partOfSpeech: .verb, example: "She refused to kowtow to unreasonable demands."),
        VocabularyWord(id: 282, word: "Licentious", definition: "Promiscuous; lacking moral restraint", partOfSpeech: .adjective, example: "The novel depicted the licentious behavior of the aristocracy."),
        VocabularyWord(id: 283, word: "Machination", definition: "A scheming plot", partOfSpeech: .noun, example: "The machinations of the villain were finally exposed."),
        VocabularyWord(id: 284, word: "Nabob", definition: "A wealthy, influential person", partOfSpeech: .noun, example: "The nabobs of industry gathered at the exclusive club."),
        VocabularyWord(id: 285, word: "Obdurate", definition: "Stubbornly refusing to change", partOfSpeech: .adjective, example: "The obdurate negotiator would not compromise."),
        VocabularyWord(id: 286, word: "Parvenu", definition: "A person of humble origins who has gained wealth", partOfSpeech: .noun, example: "Old money families looked down on the parvenu."),
        VocabularyWord(id: 287, word: "Quaff", definition: "To drink heartily", partOfSpeech: .verb, example: "They quaffed ale at the medieval festival."),
        VocabularyWord(id: 288, word: "Rebarbative", definition: "Causing annoyance or irritation", partOfSpeech: .adjective, example: "The rebarbative rules frustrated new employees."),
        VocabularyWord(id: 289, word: "Sedulous", definition: "Showing dedication and diligence", partOfSpeech: .adjective, example: "Her sedulous work ethic earned her a promotion."),
        VocabularyWord(id: 290, word: "Tyro", definition: "A beginner or novice", partOfSpeech: .noun, example: "Even as a tyro, she showed remarkable talent."),
        VocabularyWord(id: 291, word: "Umbrage", definition: "Offense or annoyance", partOfSpeech: .noun, example: "He took umbrage at the implication of dishonesty."),
        VocabularyWord(id: 292, word: "Vituperate", definition: "To blame or insult in strong language", partOfSpeech: .verb, example: "Critics vituperated the policy in harsh terms."),
        VocabularyWord(id: 293, word: "Winnow", definition: "To reduce by removing unwanted parts", partOfSpeech: .verb, example: "The committee winnowed the applications to a shortlist."),
        VocabularyWord(id: 294, word: "Animus", definition: "Hostility; motivating spirit", partOfSpeech: .noun, example: "There was clear animus between the rival factions."),
        VocabularyWord(id: 295, word: "Bloviate", definition: "To speak pompously at length", partOfSpeech: .verb, example: "The senator bloviated for hours without saying much."),
        VocabularyWord(id: 296, word: "Cavil", definition: "To make petty objections", partOfSpeech: .verb, example: "Stop caviling about minor details and focus on the big picture."),
        VocabularyWord(id: 297, word: "Desuetude", definition: "A state of disuse", partOfSpeech: .noun, example: "The ancient practice has fallen into desuetude."),
        VocabularyWord(id: 298, word: "Excoriate", definition: "To criticize severely", partOfSpeech: .verb, example: "The review excoriated the director's latest film."),
        VocabularyWord(id: 299, word: "Fatuous", definition: "Silly and pointless", partOfSpeech: .adjective, example: "His fatuous remarks added nothing to the conversation."),
        VocabularyWord(id: 300, word: "Genuflection", definition: "The act of bending the knee in reverence", partOfSpeech: .noun, example: "The ceremony required a genuflection before the altar."),
        VocabularyWord(id: 301, word: "Hubris", definition: "Excessive pride or self-confidence", partOfSpeech: .noun, example: "His hubris led to his eventual downfall."),
        VocabularyWord(id: 302, word: "Importunate", definition: "Persistent, especially to the point of annoyance", partOfSpeech: .adjective, example: "The importunate salesman would not take no for an answer."),
        VocabularyWord(id: 303, word: "Jaundiced", definition: "Affected by bitterness or resentment", partOfSpeech: .adjective, example: "Years of disappointment gave him a jaundiced view of politics."),
        VocabularyWord(id: 304, word: "Kleptocracy", definition: "Government by thieves", partOfSpeech: .noun, example: "The kleptocracy siphoned off public funds for years."),
        VocabularyWord(id: 305, word: "Logomachy", definition: "An argument about words", partOfSpeech: .noun, example: "The debate devolved into logomachy over definitions."),
        VocabularyWord(id: 306, word: "Milieu", definition: "A person's social environment", partOfSpeech: .noun, example: "The artistic milieu of Paris nurtured his creativity."),
        VocabularyWord(id: 307, word: "Noblesse oblige", definition: "The obligation of the privileged to help others", partOfSpeech: .phrase, example: "A sense of noblesse oblige drove her philanthropy."),
        VocabularyWord(id: 308, word: "Officious", definition: "Asserting authority in an annoying way", partOfSpeech: .adjective, example: "The officious clerk demanded unnecessary documentation."),
        VocabularyWord(id: 309, word: "Penchant", definition: "A strong inclination or liking", partOfSpeech: .noun, example: "She has a penchant for vintage clothing."),
        VocabularyWord(id: 310, word: "Querulant", definition: "A habitual complainer", partOfSpeech: .noun, example: "The querulant filed another complaint with management."),
        VocabularyWord(id: 311, word: "Refractory", definition: "Stubborn; resistant to authority", partOfSpeech: .adjective, example: "The refractory patient refused to follow medical advice."),
        VocabularyWord(id: 312, word: "Sangfroid", definition: "Composure in dangerous situations", partOfSpeech: .noun, example: "She handled the crisis with remarkable sangfroid."),
        VocabularyWord(id: 313, word: "Tenet", definition: "A principle or belief held by a group", partOfSpeech: .noun, example: "Freedom of speech is a fundamental tenet of democracy."),
        VocabularyWord(id: 314, word: "Ungainly", definition: "Clumsy; lacking grace", partOfSpeech: .adjective, example: "The ungainly teenager grew into a graceful athlete."),
        VocabularyWord(id: 315, word: "Vicissitude", definition: "A change of circumstances, typically unwelcome", partOfSpeech: .noun, example: "The business survived many vicissitudes over the decades."),
        VocabularyWord(id: 316, word: "Welter", definition: "A confused mass; to be in turmoil", partOfSpeech: .noun, example: "The news created a welter of conflicting emotions."),
        VocabularyWord(id: 317, word: "Antipathy", definition: "A deep-seated feeling of dislike", partOfSpeech: .noun, example: "There was clear antipathy between the two rivals."),
        VocabularyWord(id: 318, word: "Blandishment", definition: "Flattery intended to persuade", partOfSpeech: .noun, example: "No amount of blandishment could change her mind."),
        VocabularyWord(id: 319, word: "Categorical", definition: "Unambiguously explicit and direct", partOfSpeech: .adjective, example: "She gave a categorical denial of the allegations."),
        VocabularyWord(id: 320, word: "Diffident", definition: "Modest or shy; lacking self-confidence", partOfSpeech: .adjective, example: "The diffident student rarely spoke up in class."),
        VocabularyWord(id: 321, word: "Edify", definition: "To instruct or improve morally or intellectually", partOfSpeech: .verb, example: "The lecture was meant to edify as well as entertain."),
        VocabularyWord(id: 322, word: "Feckless", definition: "Lacking initiative or strength of character", partOfSpeech: .adjective, example: "The feckless manager avoided making any decisions."),
        VocabularyWord(id: 323, word: "Grandiloquent", definition: "Pompous or extravagant in language", partOfSpeech: .adjective, example: "His grandiloquent speeches were style over substance."),
        VocabularyWord(id: 324, word: "Homogeneous", definition: "Of the same kind; uniform", partOfSpeech: .adjective, example: "The homogeneous mixture blended perfectly."),
        VocabularyWord(id: 325, word: "Impecunious", definition: "Having little or no money", partOfSpeech: .adjective, example: "The impecunious artist survived on the generosity of friends."),
        VocabularyWord(id: 326, word: "Jurisprudence", definition: "The theory and philosophy of law", partOfSpeech: .noun, example: "Her expertise in jurisprudence informed the ruling."),
        VocabularyWord(id: 327, word: "Lugubrious", definition: "Looking or sounding sad and dismal", partOfSpeech: .adjective, example: "The lugubrious music set a somber mood."),
        VocabularyWord(id: 328, word: "Mendicant", definition: "A beggar", partOfSpeech: .noun, example: "Mendicants gathered near the temple for alms."),
        VocabularyWord(id: 329, word: "Nonpareil", definition: "Having no match or equal; unrivaled", partOfSpeech: .adjective, example: "Her nonpareil talent made her a star."),
        VocabularyWord(id: 330, word: "Obtuse", definition: "Annoyingly insensitive or slow to understand", partOfSpeech: .adjective, example: "He was too obtuse to notice her discomfort."),
        VocabularyWord(id: 331, word: "Penurious", definition: "Extremely poor; stingy", partOfSpeech: .adjective, example: "The penurious miser counted every penny."),
        VocabularyWord(id: 332, word: "Quiddity", definition: "The inherent nature of something", partOfSpeech: .noun, example: "Understanding the quiddity of the problem took time."),
        VocabularyWord(id: 333, word: "Ratiocination", definition: "The process of exact thinking", partOfSpeech: .noun, example: "Sherlock Holmes was famous for his ratiocination."),
        VocabularyWord(id: 334, word: "Somnolent", definition: "Sleepy; inducing drowsiness", partOfSpeech: .adjective, example: "The somnolent afternoon made concentration difficult."),
        VocabularyWord(id: 335, word: "Tautology", definition: "The saying of the same thing twice in different words", partOfSpeech: .noun, example: "'Free gift' is a common tautology in advertising."),
        VocabularyWord(id: 336, word: "Ululate", definition: "To howl or wail", partOfSpeech: .verb, example: "Mourners ululated at the funeral procession."),
        VocabularyWord(id: 337, word: "Vainglorious", definition: "Excessively proud of oneself", partOfSpeech: .adjective, example: "The vainglorious leader demanded constant praise."),
        VocabularyWord(id: 338, word: "Winsome", definition: "Attractive or appealing in a fresh way", partOfSpeech: .adjective, example: "Her winsome smile charmed everyone she met."),
        VocabularyWord(id: 339, word: "Acerbic", definition: "Sharp and forthright in speech", partOfSpeech: .adjective, example: "The critic was known for his acerbic reviews."),
        VocabularyWord(id: 340, word: "Bellicose", definition: "Demonstrating aggression; warlike", partOfSpeech: .adjective, example: "The bellicose rhetoric raised tensions between nations."),
        VocabularyWord(id: 341, word: "Contumacious", definition: "Stubbornly disobedient", partOfSpeech: .adjective, example: "The contumacious defendant ignored the court order."),
        VocabularyWord(id: 342, word: "Dyspeptic", definition: "Bad-tempered or gloomy", partOfSpeech: .adjective, example: "His dyspeptic outlook colored all his interactions."),
        VocabularyWord(id: 343, word: "Eschatology", definition: "The part of theology concerned with death and destiny", partOfSpeech: .noun, example: "The professor lectured on eschatology and end-times beliefs."),
        VocabularyWord(id: 344, word: "Fustian", definition: "Pompous or pretentious speech or writing", partOfSpeech: .noun, example: "His fustian writing obscured rather than clarified his ideas."),
        VocabularyWord(id: 345, word: "Gossamer", definition: "Light, delicate, and insubstantial", partOfSpeech: .adjective, example: "The gossamer wings of the dragonfly caught the light."),
        VocabularyWord(id: 346, word: "Hidebound", definition: "Unwilling to change because of tradition", partOfSpeech: .adjective, example: "The hidebound institution resisted all reforms."),
        VocabularyWord(id: 347, word: "Insouciance", definition: "Casual lack of concern", partOfSpeech: .noun, example: "His insouciance about deadlines frustrated his colleagues."),
        VocabularyWord(id: 348, word: "Jeremiad", definition: "A long, mournful complaint", partOfSpeech: .noun, example: "The editorial was a jeremiad against modern technology."),
        VocabularyWord(id: 349, word: "Limn", definition: "To depict or describe in detail", partOfSpeech: .verb, example: "The author limned the characters with precision."),
        VocabularyWord(id: 350, word: "Malediction", definition: "A curse", partOfSpeech: .noun, example: "The witch's malediction hung over the village."),
        VocabularyWord(id: 351, word: "Nefarious", definition: "Wicked or criminal", partOfSpeech: .adjective, example: "The nefarious scheme was finally uncovered by investigators."),
        VocabularyWord(id: 352, word: "Obsequious", definition: "Obedient to an excessive degree", partOfSpeech: .adjective, example: "The obsequious assistant agreed with everything the boss said."),
        VocabularyWord(id: 353, word: "Perfidy", definition: "Deceitfulness; untrustworthiness", partOfSpeech: .noun, example: "The perfidy of the spy was eventually discovered."),
        VocabularyWord(id: 354, word: "Quiescence", definition: "A state of inactivity or dormancy", partOfSpeech: .noun, example: "The market entered a period of quiescence."),
        VocabularyWord(id: 355, word: "Recumbent", definition: "Lying down", partOfSpeech: .adjective, example: "The recumbent figure on the couch appeared to be sleeping."),
        VocabularyWord(id: 356, word: "Supine", definition: "Lying face upward; failing to act due to laziness", partOfSpeech: .adjective, example: "The supine response to the crisis disappointed many."),
        VocabularyWord(id: 357, word: "Transmute", definition: "To change in form, nature, or substance", partOfSpeech: .verb, example: "Alchemists tried to transmute lead into gold."),
        VocabularyWord(id: 358, word: "Untrammeled", definition: "Not restricted or hampered", partOfSpeech: .adjective, example: "Artists flourished in the untrammeled creative environment."),
        VocabularyWord(id: 359, word: "Venal", definition: "Showing susceptibility to bribery", partOfSpeech: .adjective, example: "The venal judges were removed from the bench."),
        VocabularyWord(id: 360, word: "Wizened", definition: "Shriveled or wrinkled with age", partOfSpeech: .adjective, example: "The wizened old man shared stories of the past."),
        VocabularyWord(id: 361, word: "Acuity", definition: "Sharpness of thought, vision, or hearing", partOfSpeech: .noun, example: "Her mental acuity remained sharp into her nineties."),
        VocabularyWord(id: 362, word: "Bilious", definition: "Spiteful; bad-tempered", partOfSpeech: .adjective, example: "His bilious disposition kept people at a distance."),
        VocabularyWord(id: 363, word: "Circumlocution", definition: "The use of many words where fewer would do", partOfSpeech: .noun, example: "Avoid circumlocution in professional writing."),
        VocabularyWord(id: 364, word: "Dolorous", definition: "Feeling or expressing great sorrow", partOfSpeech: .adjective, example: "The dolorous music moved the audience to tears."),
    ]

    /// Returns the word for today based on the day of the year
    static func todaysWord() -> VocabularyWord {
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: Date()) ?? 1
        let index = (dayOfYear - 1) % words.count
        return words[index]
    }

    /// Returns the word for a specific date
    static func wordForDate(_ date: Date) -> VocabularyWord {
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: date) ?? 1
        let index = (dayOfYear - 1) % words.count
        return words[index]
    }
}
