//
//  VocabularyData.swift
//  vocab-builder
//
//  Created by Michael Zhao on 1/16/26.
//

import Foundation

struct VocabularyWord: Codable, Identifiable {
    let id: Int
    let word: String
    let definition: String
}

struct VocabularyData {
    static let words: [VocabularyWord] = [
        VocabularyWord(id: 0, word: "Epistemic", definition: "Relating to knowledge or the conditions for acquiring it"),
        VocabularyWord(id: 1, word: "Liminal", definition: "Occupying a position at a threshold between two states"),
        VocabularyWord(id: 2, word: "Shibboleth", definition: "A custom or belief that distinguishes a particular group"),
        VocabularyWord(id: 3, word: "Palimpsest", definition: "Something reused but bearing traces of its earlier form"),
        VocabularyWord(id: 4, word: "Ineluctable", definition: "Unable to be resisted or avoided; inevitable"),
        VocabularyWord(id: 5, word: "Synecdoche", definition: "A part used to represent the whole, or vice versa"),
        VocabularyWord(id: 6, word: "Apophenia", definition: "Perceiving meaningful connections between unrelated things"),
        VocabularyWord(id: 7, word: "Proleptic", definition: "Anticipating and answering objections in advance"),
        VocabularyWord(id: 8, word: "Cathexis", definition: "The concentration of mental energy on a person or idea"),
        VocabularyWord(id: 9, word: "Hermeneutic", definition: "Concerning interpretation, especially of texts or meaning"),
        VocabularyWord(id: 10, word: "Simulacrum", definition: "An image or representation of something; an unsatisfying imitation"),
        VocabularyWord(id: 11, word: "Praxis", definition: "The practical application of theory or belief"),
        VocabularyWord(id: 12, word: "Teleological", definition: "Explaining phenomena by their purpose rather than cause"),
        VocabularyWord(id: 13, word: "Etiolated", definition: "Made weak or pale through lack of light or vitality"),
        VocabularyWord(id: 14, word: "Aporia", definition: "An irresolvable internal contradiction in a text or argument"),
        VocabularyWord(id: 15, word: "Interstitial", definition: "Relating to or occupying small spaces between things"),
        VocabularyWord(id: 16, word: "Sui generis", definition: "Unique; in a class of its own"),
        VocabularyWord(id: 17, word: "Sclerotic", definition: "Becoming rigid and resistant to change"),
        VocabularyWord(id: 18, word: "Anodyne", definition: "Unlikely to cause offense; blandly agreeable"),
        VocabularyWord(id: 19, word: "Propinquity", definition: "Nearness in place, time, or relationship"),
        VocabularyWord(id: 20, word: "Concatenate", definition: "To link together in a series or chain"),
        VocabularyWord(id: 21, word: "Peripatetic", definition: "Traveling from place to place, especially for work"),
        VocabularyWord(id: 22, word: "Solipsistic", definition: "Self-absorbed; believing only one's own mind is certain"),
        VocabularyWord(id: 23, word: "Atavistic", definition: "Reverting to something ancient or ancestral"),
        VocabularyWord(id: 24, word: "Chiasmus", definition: "A rhetorical reversal of word order for effect"),
        VocabularyWord(id: 25, word: "Entropic", definition: "Tending toward disorder or decline"),
        VocabularyWord(id: 26, word: "Adumbrate", definition: "To outline or foreshadow; to partially disclose"),
        VocabularyWord(id: 27, word: "Syncretic", definition: "Combining different beliefs, cultures, or schools of thought"),
        VocabularyWord(id: 28, word: "Tendentious", definition: "Promoting a particular cause or viewpoint"),
        VocabularyWord(id: 29, word: "Lacuna", definition: "A gap or missing portion, especially in a text"),
        VocabularyWord(id: 30, word: "Reify", definition: "To treat an abstraction as if it were concrete or real"),
        VocabularyWord(id: 31, word: "Palliative", definition: "Relieving symptoms without addressing the cause"),
        VocabularyWord(id: 32, word: "Axiomatic", definition: "Self-evidently true; unquestioned"),
        VocabularyWord(id: 33, word: "Heterodox", definition: "Not conforming to accepted standards or beliefs"),
        VocabularyWord(id: 34, word: "Apodictic", definition: "Clearly established; beyond dispute"),
        VocabularyWord(id: 35, word: "Putative", definition: "Generally considered or reputed to be"),
        VocabularyWord(id: 36, word: "Instantiate", definition: "To represent as a concrete example"),
        VocabularyWord(id: 37, word: "Metonymic", definition: "Using an attribute to stand for the thing itself"),
        VocabularyWord(id: 38, word: "Aporetic", definition: "Relating to a state of puzzlement or doubt"),
        VocabularyWord(id: 39, word: "Procrustean", definition: "Enforcing conformity through arbitrary methods"),
        VocabularyWord(id: 40, word: "Specious", definition: "Superficially plausible but actually wrong"),
        VocabularyWord(id: 41, word: "Valence", definition: "The capacity of something to interact or influence"),
        VocabularyWord(id: 42, word: "Aegis", definition: "Protection, sponsorship, or guidance"),
        VocabularyWord(id: 43, word: "Antediluvian", definition: "Extremely old-fashioned or out of date"),
        VocabularyWord(id: 44, word: "Capacious", definition: "Having much space; roomy and accommodating"),
        VocabularyWord(id: 45, word: "Desuetude", definition: "A state of disuse or inactivity"),
        VocabularyWord(id: 46, word: "Exigent", definition: "Pressing; demanding immediate attention"),
        VocabularyWord(id: 47, word: "Fungible", definition: "Interchangeable; able to be substituted"),
        VocabularyWord(id: 48, word: "Gestalt", definition: "A unified whole perceived as more than its parts"),
        VocabularyWord(id: 49, word: "Hortatory", definition: "Strongly encouraging or urging action"),
        VocabularyWord(id: 50, word: "Imprimatur", definition: "Official approval or sanction"),
        VocabularyWord(id: 51, word: "Jeremiad", definition: "A prolonged lamentation or tale of woe"),
        VocabularyWord(id: 52, word: "Kenosis", definition: "The emptying of one's will to become receptive"),
        VocabularyWord(id: 53, word: "Latent", definition: "Present but not visible or active; dormant"),
        VocabularyWord(id: 54, word: "Miasma", definition: "An oppressive atmosphere of gloom or corruption"),
        VocabularyWord(id: 55, word: "Normative", definition: "Establishing or relating to a standard"),
        VocabularyWord(id: 56, word: "Ossified", definition: "Rigid and resistant to change"),
        VocabularyWord(id: 57, word: "Paradigmatic", definition: "Serving as a typical example or model"),
        VocabularyWord(id: 58, word: "Quorum", definition: "The minimum number needed for valid proceedings"),
        VocabularyWord(id: 59, word: "Redact", definition: "To edit for publication; to obscure sensitive content"),
        VocabularyWord(id: 60, word: "Seminal", definition: "Strongly influencing later developments"),
        VocabularyWord(id: 61, word: "Tautological", definition: "Needlessly repetitive; true by definition"),
        VocabularyWord(id: 62, word: "Ulterior", definition: "Beyond what is stated; hidden"),
        VocabularyWord(id: 63, word: "Venal", definition: "Susceptible to bribery; corrupt"),
        VocabularyWord(id: 64, word: "Watershed", definition: "A turning point; a critical dividing event"),
        VocabularyWord(id: 65, word: "Apothegm", definition: "A concise saying expressing a general truth"),
        VocabularyWord(id: 66, word: "Bête noire", definition: "A person or thing particularly disliked or avoided"),
        VocabularyWord(id: 67, word: "Ceteris paribus", definition: "With all other things being equal"),
        VocabularyWord(id: 68, word: "Draconian", definition: "Excessively harsh or severe"),
        VocabularyWord(id: 69, word: "Endemic", definition: "Native to or characteristic of a particular place"),
        VocabularyWord(id: 70, word: "Fait accompli", definition: "A thing already done and beyond reversal"),
        VocabularyWord(id: 71, word: "Gravamen", definition: "The essence or most serious part of a complaint"),
        VocabularyWord(id: 72, word: "Hegemonic", definition: "Having dominant influence over others"),
        VocabularyWord(id: 73, word: "Incipient", definition: "Beginning to develop; in an early stage"),
        VocabularyWord(id: 74, word: "Juggernaut", definition: "A massive, unstoppable force"),
        VocabularyWord(id: 75, word: "Kinetic", definition: "Relating to or produced by motion"),
        VocabularyWord(id: 76, word: "Lumpen", definition: "Unthinking; relating to displaced masses"),
        VocabularyWord(id: 77, word: "Meretricious", definition: "Apparently attractive but lacking real value"),
        VocabularyWord(id: 78, word: "Nascent", definition: "Just beginning to develop"),
        VocabularyWord(id: 79, word: "Opprobrium", definition: "Harsh criticism or public disgrace"),
        VocabularyWord(id: 80, word: "Pari passu", definition: "At an equal rate or pace; side by side"),
        VocabularyWord(id: 81, word: "Querulous", definition: "Habitually complaining; petulant"),
        VocabularyWord(id: 82, word: "Redound", definition: "To contribute greatly; to return as consequence"),
        VocabularyWord(id: 83, word: "Salient", definition: "Most noticeable or important"),
        VocabularyWord(id: 84, word: "Taxonomy", definition: "A scheme of classification"),
        VocabularyWord(id: 85, word: "Umbra", definition: "A shadow; a region of complete darkness"),
        VocabularyWord(id: 86, word: "Vitiate", definition: "To impair the quality or reduce the value of"),
        VocabularyWord(id: 87, word: "Writ large", definition: "In a larger or more obvious form"),
        VocabularyWord(id: 88, word: "Abrogate", definition: "To abolish or annul by authority"),
        VocabularyWord(id: 89, word: "Bellwether", definition: "An indicator of future trends"),
        VocabularyWord(id: 90, word: "Circuitous", definition: "Taking a roundabout route; not direct"),
        VocabularyWord(id: 91, word: "Desiccated", definition: "Dried out; lacking vitality"),
        VocabularyWord(id: 92, word: "Effete", definition: "No longer effective; exhausted of vitality"),
        VocabularyWord(id: 93, word: "Fecund", definition: "Producing many ideas or offspring; fertile"),
        VocabularyWord(id: 94, word: "Gambit", definition: "An opening move; a calculated risk"),
        VocabularyWord(id: 95, word: "Hermetic", definition: "Completely sealed; protected from outside influence"),
        VocabularyWord(id: 96, word: "Invidious", definition: "Likely to cause resentment; unfairly discriminating"),
        VocabularyWord(id: 97, word: "Jettison", definition: "To abandon or discard"),
        VocabularyWord(id: 98, word: "Kismet", definition: "Fate; destiny"),
        VocabularyWord(id: 99, word: "Legerdemain", definition: "Skillful deception; sleight of hand"),
        VocabularyWord(id: 100, word: "Malfeasance", definition: "Wrongdoing, especially by a public official"),
        VocabularyWord(id: 101, word: "Nadir", definition: "The lowest point"),
        VocabularyWord(id: 102, word: "Obviate", definition: "To remove or prevent a difficulty"),
        VocabularyWord(id: 103, word: "Paradigm", definition: "A typical example or pattern of something"),
        VocabularyWord(id: 104, word: "Quintessential", definition: "Representing the most perfect example"),
        VocabularyWord(id: 105, word: "Recalcitrant", definition: "Stubbornly resistant to authority"),
        VocabularyWord(id: 106, word: "Stolid", definition: "Calm, dependable, and showing little emotion"),
        VocabularyWord(id: 107, word: "Trenchant", definition: "Vigorous, effective, and articulate"),
        VocabularyWord(id: 108, word: "Utilitarian", definition: "Designed for usefulness rather than beauty"),
        VocabularyWord(id: 109, word: "Vexed", definition: "Much debated; annoyed"),
        VocabularyWord(id: 110, word: "Zeitgeist", definition: "The defining spirit of a particular period"),
        VocabularyWord(id: 111, word: "Allocution", definition: "A formal speech, especially a warning or exhortation"),
        VocabularyWord(id: 112, word: "Bowdlerize", definition: "To remove content considered offensive"),
        VocabularyWord(id: 113, word: "Cabalistic", definition: "Having a secret or esoteric meaning"),
        VocabularyWord(id: 114, word: "Demotic", definition: "Relating to ordinary people; vernacular"),
        VocabularyWord(id: 115, word: "Effluvium", definition: "An unpleasant or harmful odor or discharge"),
        VocabularyWord(id: 116, word: "Fissiparous", definition: "Inclined to cause division or fragment"),
        VocabularyWord(id: 117, word: "Gravid", definition: "Full of meaning; pregnant with significance"),
        VocabularyWord(id: 118, word: "Heuristic", definition: "Enabling discovery through experimentation"),
        VocabularyWord(id: 119, word: "Immanent", definition: "Existing or operating within; inherent"),
        VocabularyWord(id: 120, word: "Juxtapose", definition: "To place side by side for comparison or contrast"),
        VocabularyWord(id: 121, word: "Kludge", definition: "An awkward but effective solution to a problem"),
        VocabularyWord(id: 122, word: "Lucubration", definition: "Laborious study or meditation"),
        VocabularyWord(id: 123, word: "Malapropism", definition: "Mistaken use of a word for a similar-sounding one"),
        VocabularyWord(id: 124, word: "Nostrum", definition: "A pet scheme; a questionable remedy"),
        VocabularyWord(id: 125, word: "Otiose", definition: "Serving no practical purpose; idle"),
        VocabularyWord(id: 126, word: "Persiflage", definition: "Light, mocking banter"),
        VocabularyWord(id: 127, word: "Quotidian", definition: "Ordinary; everyday"),
        VocabularyWord(id: 128, word: "Rapprochement", definition: "The establishment of cordial relations"),
        VocabularyWord(id: 129, word: "Sartorial", definition: "Relating to tailoring or clothing style"),
        VocabularyWord(id: 130, word: "Tendentious", definition: "Expressing a strongly biased point of view"),
        VocabularyWord(id: 131, word: "Unctuous", definition: "Excessively flattering; oily"),
        VocabularyWord(id: 132, word: "Vicissitude", definition: "A change of circumstances, typically unwelcome"),
        VocabularyWord(id: 133, word: "Weltanschauung", definition: "A comprehensive worldview or philosophy"),
        VocabularyWord(id: 134, word: "Ameliorate", definition: "To make something bad better"),
        VocabularyWord(id: 135, word: "Bildungsroman", definition: "A novel about a person's formative years"),
        VocabularyWord(id: 136, word: "Calumny", definition: "A false statement damaging to reputation"),
        VocabularyWord(id: 137, word: "Desideratum", definition: "Something considered necessary or desired"),
        VocabularyWord(id: 138, word: "Emollient", definition: "Having a softening or soothing effect"),
        VocabularyWord(id: 139, word: "Flâneur", definition: "One who strolls and observes society"),
        VocabularyWord(id: 140, word: "Granular", definition: "Consisting of fine details; highly specific"),
        VocabularyWord(id: 141, word: "Homologous", definition: "Having the same relation or structure"),
        VocabularyWord(id: 142, word: "Impugn", definition: "To dispute the truth or validity of"),
        VocabularyWord(id: 143, word: "Jocund", definition: "Cheerful and lighthearted"),
        VocabularyWord(id: 144, word: "Kinesthesia", definition: "Awareness of body position and movement"),
        VocabularyWord(id: 145, word: "Laudatory", definition: "Expressing praise"),
        VocabularyWord(id: 146, word: "Morphology", definition: "The study of forms and structures"),
        VocabularyWord(id: 147, word: "Neologism", definition: "A newly coined word or expression"),
        VocabularyWord(id: 148, word: "Ontological", definition: "Relating to the nature of being or existence"),
        VocabularyWord(id: 149, word: "Propitious", definition: "Indicating a favorable outcome"),
        VocabularyWord(id: 150, word: "Quiddity", definition: "The essential nature of something"),
        VocabularyWord(id: 151, word: "Recondite", definition: "Obscure; known only to a few"),
        VocabularyWord(id: 152, word: "Solecism", definition: "A grammatical mistake or breach of etiquette"),
        VocabularyWord(id: 153, word: "Tergiversate", definition: "To change repeatedly one's attitude or opinions"),
        VocabularyWord(id: 154, word: "Usufruct", definition: "The right to use another's property"),
        VocabularyWord(id: 155, word: "Verisimilitude", definition: "The appearance of being true or real"),
        VocabularyWord(id: 156, word: "Whilom", definition: "Former; erstwhile"),
        VocabularyWord(id: 157, word: "Abnegate", definition: "To renounce or reject"),
        VocabularyWord(id: 158, word: "Brio", definition: "Vigor and vivacity"),
        VocabularyWord(id: 159, word: "Canard", definition: "An unfounded rumor or story"),
        VocabularyWord(id: 160, word: "Détente", definition: "The easing of hostility between countries"),
        VocabularyWord(id: 161, word: "Ersatz", definition: "An inferior substitute"),
        VocabularyWord(id: 162, word: "Fractious", definition: "Irritable and quarrelsome"),
        VocabularyWord(id: 163, word: "Galvanic", definition: "Sudden and dramatic; stimulating"),
        VocabularyWord(id: 164, word: "Hieratic", definition: "Of or concerning priests; formal and stylized"),
        VocabularyWord(id: 165, word: "Inchoate", definition: "Just begun; not fully formed"),
        VocabularyWord(id: 166, word: "Jejune", definition: "Naive; lacking substance or interest"),
        VocabularyWord(id: 167, word: "Kyriarchy", definition: "A social system built on intersecting oppressions"),
        VocabularyWord(id: 168, word: "Limpid", definition: "Clear and transparent; easily understood"),
        VocabularyWord(id: 169, word: "Mandarin", definition: "A powerful official; an influential intellectual"),
        VocabularyWord(id: 170, word: "Numinous", definition: "Having a strong spiritual or religious quality"),
        VocabularyWord(id: 171, word: "Oppugn", definition: "To call into question; to oppose"),
        VocabularyWord(id: 172, word: "Prescient", definition: "Having knowledge of events before they occur"),
        VocabularyWord(id: 173, word: "Quondam", definition: "Former"),
        VocabularyWord(id: 174, word: "Recusant", definition: "Refusing to submit to authority"),
        VocabularyWord(id: 175, word: "Sanguine", definition: "Optimistic, especially in a difficult situation"),
        VocabularyWord(id: 176, word: "Tertiary", definition: "Third in order or level"),
        VocabularyWord(id: 177, word: "Univocal", definition: "Having only one meaning; unambiguous"),
        VocabularyWord(id: 178, word: "Volte-face", definition: "A sudden reversal of opinion or position"),
        VocabularyWord(id: 179, word: "Wunderkind", definition: "A young person who achieves great success"),
        VocabularyWord(id: 180, word: "Antinomy", definition: "A contradiction between two reasonable principles"),
        VocabularyWord(id: 181, word: "Bromide", definition: "A trite, unoriginal statement"),
        VocabularyWord(id: 182, word: "Concatenation", definition: "A series of linked things or events"),
        VocabularyWord(id: 183, word: "Didactic", definition: "Intended to teach or instruct"),
        VocabularyWord(id: 184, word: "Elide", definition: "To omit or merge sounds; to ignore"),
        VocabularyWord(id: 185, word: "Fugacious", definition: "Tending to disappear; fleeting"),
        VocabularyWord(id: 186, word: "Geist", definition: "The spirit of an individual or era"),
        VocabularyWord(id: 187, word: "Heterogeneous", definition: "Diverse in character or content"),
        VocabularyWord(id: 188, word: "Ineffable", definition: "Too great or extreme to be expressed in words"),
        VocabularyWord(id: 189, word: "Juxtaposition", definition: "The fact of placing things close together for contrast"),
        VocabularyWord(id: 190, word: "Kakistocracy", definition: "Government by the least qualified citizens"),
        VocabularyWord(id: 191, word: "Laconic", definition: "Using very few words"),
        VocabularyWord(id: 192, word: "Martinet", definition: "A strict disciplinarian"),
        VocabularyWord(id: 193, word: "Necromancy", definition: "Communication with the dead; sorcery"),
        VocabularyWord(id: 194, word: "Obsequy", definition: "A funeral rite"),
        VocabularyWord(id: 195, word: "Perspicuous", definition: "Clearly expressed and easily understood"),
        VocabularyWord(id: 196, word: "Quiescent", definition: "In a state of quiet inactivity"),
        VocabularyWord(id: 197, word: "Realpolitik", definition: "Politics based on practical rather than moral aims"),
        VocabularyWord(id: 198, word: "Shibboleth", definition: "A belief or practice that distinguishes a group"),
        VocabularyWord(id: 199, word: "Truculent", definition: "Eager to argue or fight; aggressively defiant"),
        VocabularyWord(id: 200, word: "Umbrageous", definition: "Easily offended; providing shade"),
        VocabularyWord(id: 201, word: "Vouchsafe", definition: "To give or grant something in a condescending way"),
        VocabularyWord(id: 202, word: "Waylay", definition: "To stop and detain someone unexpectedly"),
        VocabularyWord(id: 203, word: "Acephalous", definition: "Without a leader or head"),
        VocabularyWord(id: 204, word: "Belie", definition: "To fail to give a true impression of"),
        VocabularyWord(id: 205, word: "Chicanery", definition: "Deception by clever legal maneuvering"),
        VocabularyWord(id: 206, word: "Denouement", definition: "The final resolution of a plot"),
        VocabularyWord(id: 207, word: "Ebullience", definition: "The quality of being cheerful and full of energy"),
        VocabularyWord(id: 208, word: "Febrile", definition: "Having or showing symptoms of fever; feverishly excited"),
        VocabularyWord(id: 209, word: "Gainsay", definition: "To deny or contradict"),
        VocabularyWord(id: 210, word: "Hagiography", definition: "An idealized biography; excessive admiration"),
        VocabularyWord(id: 211, word: "Imprimatur", definition: "Official approval or sanction"),
        VocabularyWord(id: 212, word: "Juvenilia", definition: "Works produced by an author in youth"),
        VocabularyWord(id: 213, word: "Kvetch", definition: "To complain persistently"),
        VocabularyWord(id: 214, word: "Leitmotif", definition: "A recurring theme in a work or a person's life"),
        VocabularyWord(id: 215, word: "Maudlin", definition: "Self-pityingly sentimental"),
        VocabularyWord(id: 216, word: "Nexus", definition: "A connection or series of connections"),
        VocabularyWord(id: 217, word: "Obloquy", definition: "Strong public criticism or verbal abuse"),
        VocabularyWord(id: 218, word: "Paladin", definition: "A champion of a cause; a heroic advocate"),
        VocabularyWord(id: 219, word: "Quixotic", definition: "Exceedingly idealistic; unrealistic"),
        VocabularyWord(id: 220, word: "Recidivist", definition: "One who repeatedly commits crimes or errors"),
        VocabularyWord(id: 221, word: "Sacrosanct", definition: "Too important to be changed or interfered with"),
        VocabularyWord(id: 222, word: "Torpor", definition: "A state of physical or mental inactivity"),
        VocabularyWord(id: 223, word: "Uxoricide", definition: "The killing of one's wife"),
        VocabularyWord(id: 224, word: "Verbiage", definition: "Excessive or unnecessarily complex language"),
        VocabularyWord(id: 225, word: "Whelm", definition: "To engulf or submerge completely"),
        VocabularyWord(id: 226, word: "Antipodal", definition: "Relating to opposite sides; diametrically opposed"),
        VocabularyWord(id: 227, word: "Bifurcate", definition: "To divide into two branches"),
        VocabularyWord(id: 228, word: "Comity", definition: "Mutual courtesy and consideration"),
        VocabularyWord(id: 229, word: "Dilatory", definition: "Slow to act; intended to cause delay"),
        VocabularyWord(id: 230, word: "Epicene", definition: "Having characteristics of both sexes; effeminate"),
        VocabularyWord(id: 231, word: "Froideur", definition: "Coldness or aloofness in manner"),
        VocabularyWord(id: 232, word: "Gnomic", definition: "Expressed in short, pithy sayings"),
        VocabularyWord(id: 233, word: "Haptic", definition: "Relating to the sense of touch"),
        VocabularyWord(id: 234, word: "Inimical", definition: "Tending to obstruct or harm; hostile"),
        VocabularyWord(id: 235, word: "Jocosity", definition: "The quality of being humorous"),
        VocabularyWord(id: 236, word: "Lachrymose", definition: "Given to weeping; tearful"),
        VocabularyWord(id: 237, word: "Meliorism", definition: "Belief that the world can be improved by human effort"),
        VocabularyWord(id: 238, word: "Nugatory", definition: "Of no value or importance"),
        VocabularyWord(id: 239, word: "Orotund", definition: "Full and round in sound; pompous"),
        VocabularyWord(id: 240, word: "Palaver", definition: "Prolonged idle discussion"),
        VocabularyWord(id: 241, word: "Qua", definition: "In the capacity of"),
        VocabularyWord(id: 242, word: "Recrudescence", definition: "The revival of something unwelcome"),
        VocabularyWord(id: 243, word: "Simulacrum", definition: "An unsatisfying imitation or substitute"),
        VocabularyWord(id: 244, word: "Trope", definition: "A common or recurring theme or device"),
        VocabularyWord(id: 245, word: "Ukase", definition: "An arbitrary command"),
        VocabularyWord(id: 246, word: "Velleity", definition: "A wish without accompanying action"),
        VocabularyWord(id: 247, word: "Wonted", definition: "Habitual; usual"),
        VocabularyWord(id: 248, word: "Apostate", definition: "One who abandons a belief or principle"),
        VocabularyWord(id: 249, word: "Bathetic", definition: "Producing an effect of anticlimax"),
        VocabularyWord(id: 250, word: "Callow", definition: "Inexperienced and immature"),
        VocabularyWord(id: 251, word: "Declivity", definition: "A downward slope"),
        VocabularyWord(id: 252, word: "Encomium", definition: "A speech or piece of writing that praises highly"),
        VocabularyWord(id: 253, word: "Fulsome", definition: "Excessively flattering; abundant to excess"),
        VocabularyWord(id: 254, word: "Genuflect", definition: "To show deep respect; to kneel"),
        VocabularyWord(id: 255, word: "Hortatory", definition: "Strongly encouraging or urging"),
        VocabularyWord(id: 256, word: "Inimitable", definition: "Impossible to imitate; unique"),
        VocabularyWord(id: 257, word: "Jingoistic", definition: "Extremely patriotic; bellicose"),
        VocabularyWord(id: 258, word: "Kith", definition: "One's friends, acquaintances, and relations"),
        VocabularyWord(id: 259, word: "Lassitude", definition: "Physical or mental weariness"),
        VocabularyWord(id: 260, word: "Maunder", definition: "To talk or move aimlessly"),
        VocabularyWord(id: 261, word: "Nescient", definition: "Lacking knowledge; ignorant"),
        VocabularyWord(id: 262, word: "Obstreperous", definition: "Noisy and difficult to control"),
        VocabularyWord(id: 263, word: "Pecuniary", definition: "Relating to money"),
        VocabularyWord(id: 264, word: "Quietus", definition: "Death or something that causes death; a final settlement"),
        VocabularyWord(id: 265, word: "Raffish", definition: "Unconventional and slightly disreputable but appealing"),
        VocabularyWord(id: 266, word: "Saturnine", definition: "Gloomy; sluggish in temperament"),
        VocabularyWord(id: 267, word: "Tutelage", definition: "Protection or guardianship; instruction"),
        VocabularyWord(id: 268, word: "Usury", definition: "Lending money at unreasonably high interest"),
        VocabularyWord(id: 269, word: "Vagary", definition: "An unpredictable change; a whim"),
        VocabularyWord(id: 270, word: "Waspish", definition: "Readily irritated; sharply critical"),
        VocabularyWord(id: 271, word: "Adjunct", definition: "An additional but not essential part"),
        VocabularyWord(id: 272, word: "Benighted", definition: "Ignorant; in a state of intellectual darkness"),
        VocabularyWord(id: 273, word: "Cogent", definition: "Clear, logical, and convincing"),
        VocabularyWord(id: 274, word: "Demur", definition: "To raise objections or show reluctance"),
        VocabularyWord(id: 275, word: "Equivocate", definition: "To use ambiguous language to deceive"),
        VocabularyWord(id: 276, word: "Fiduciary", definition: "Involving trust, especially regarding money"),
        VocabularyWord(id: 277, word: "Gauche", definition: "Lacking social grace; tactless"),
        VocabularyWord(id: 278, word: "Hegemony", definition: "Dominance by one group over others"),
        VocabularyWord(id: 279, word: "Infelicitous", definition: "Unfortunate; inappropriate"),
        VocabularyWord(id: 280, word: "Jargon", definition: "Special words used by a profession or group"),
        VocabularyWord(id: 281, word: "Kowtow", definition: "To act in a submissive manner"),
        VocabularyWord(id: 282, word: "Licentious", definition: "Promiscuous; lacking moral restraint"),
        VocabularyWord(id: 283, word: "Machination", definition: "A scheming plot"),
        VocabularyWord(id: 284, word: "Nabob", definition: "A wealthy, influential person"),
        VocabularyWord(id: 285, word: "Obdurate", definition: "Stubbornly refusing to change"),
        VocabularyWord(id: 286, word: "Parvenu", definition: "A person of humble origins who has gained wealth"),
        VocabularyWord(id: 287, word: "Quaff", definition: "To drink heartily"),
        VocabularyWord(id: 288, word: "Rebarbative", definition: "Causing annoyance or irritation"),
        VocabularyWord(id: 289, word: "Sedulous", definition: "Showing dedication and diligence"),
        VocabularyWord(id: 290, word: "Tyro", definition: "A beginner or novice"),
        VocabularyWord(id: 291, word: "Umbrage", definition: "Offense or annoyance"),
        VocabularyWord(id: 292, word: "Vituperate", definition: "To blame or insult in strong language"),
        VocabularyWord(id: 293, word: "Winnow", definition: "To reduce by removing unwanted parts"),
        VocabularyWord(id: 294, word: "Animus", definition: "Hostility; motivating spirit"),
        VocabularyWord(id: 295, word: "Bloviate", definition: "To speak pompously at length"),
        VocabularyWord(id: 296, word: "Cavil", definition: "To make petty objections"),
        VocabularyWord(id: 297, word: "Desuetude", definition: "A state of disuse"),
        VocabularyWord(id: 298, word: "Excoriate", definition: "To criticize severely"),
        VocabularyWord(id: 299, word: "Fatuous", definition: "Silly and pointless"),
        VocabularyWord(id: 300, word: "Genuflection", definition: "The act of bending the knee in reverence"),
        VocabularyWord(id: 301, word: "Hubris", definition: "Excessive pride or self-confidence"),
        VocabularyWord(id: 302, word: "Importunate", definition: "Persistent, especially to the point of annoyance"),
        VocabularyWord(id: 303, word: "Jaundiced", definition: "Affected by bitterness or resentment"),
        VocabularyWord(id: 304, word: "Kleptocracy", definition: "Government by thieves"),
        VocabularyWord(id: 305, word: "Logomachy", definition: "An argument about words"),
        VocabularyWord(id: 306, word: "Milieu", definition: "A person's social environment"),
        VocabularyWord(id: 307, word: "Noblesse oblige", definition: "The obligation of the privileged to help others"),
        VocabularyWord(id: 308, word: "Officious", definition: "Asserting authority in an annoying way"),
        VocabularyWord(id: 309, word: "Penchant", definition: "A strong inclination or liking"),
        VocabularyWord(id: 310, word: "Querulant", definition: "A habitual complainer"),
        VocabularyWord(id: 311, word: "Refractory", definition: "Stubborn; resistant to authority"),
        VocabularyWord(id: 312, word: "Sangfroid", definition: "Composure in dangerous situations"),
        VocabularyWord(id: 313, word: "Tenet", definition: "A principle or belief held by a group"),
        VocabularyWord(id: 314, word: "Ungainly", definition: "Clumsy; lacking grace"),
        VocabularyWord(id: 315, word: "Vicissitude", definition: "A change of circumstances, typically unwelcome"),
        VocabularyWord(id: 316, word: "Welter", definition: "A confused mass; to be in turmoil"),
        VocabularyWord(id: 317, word: "Antipathy", definition: "A deep-seated feeling of dislike"),
        VocabularyWord(id: 318, word: "Blandishment", definition: "Flattery intended to persuade"),
        VocabularyWord(id: 319, word: "Categorical", definition: "Unambiguously explicit and direct"),
        VocabularyWord(id: 320, word: "Diffident", definition: "Modest or shy; lacking self-confidence"),
        VocabularyWord(id: 321, word: "Edify", definition: "To instruct or improve morally or intellectually"),
        VocabularyWord(id: 322, word: "Feckless", definition: "Lacking initiative or strength of character"),
        VocabularyWord(id: 323, word: "Grandiloquent", definition: "Pompous or extravagant in language"),
        VocabularyWord(id: 324, word: "Homogeneous", definition: "Of the same kind; uniform"),
        VocabularyWord(id: 325, word: "Impecunious", definition: "Having little or no money"),
        VocabularyWord(id: 326, word: "Jurisprudence", definition: "The theory and philosophy of law"),
        VocabularyWord(id: 327, word: "Lugubrious", definition: "Looking or sounding sad and dismal"),
        VocabularyWord(id: 328, word: "Mendicant", definition: "A beggar"),
        VocabularyWord(id: 329, word: "Nonpareil", definition: "Having no match or equal; unrivaled"),
        VocabularyWord(id: 330, word: "Obtuse", definition: "Annoyingly insensitive or slow to understand"),
        VocabularyWord(id: 331, word: "Penurious", definition: "Extremely poor; stingy"),
        VocabularyWord(id: 332, word: "Quiddity", definition: "The inherent nature of something"),
        VocabularyWord(id: 333, word: "Ratiocination", definition: "The process of exact thinking"),
        VocabularyWord(id: 334, word: "Somnolent", definition: "Sleepy; inducing drowsiness"),
        VocabularyWord(id: 335, word: "Tautology", definition: "The saying of the same thing twice in different words"),
        VocabularyWord(id: 336, word: "Ululate", definition: "To howl or wail"),
        VocabularyWord(id: 337, word: "Vainglorious", definition: "Excessively proud of oneself"),
        VocabularyWord(id: 338, word: "Winsome", definition: "Attractive or appealing in a fresh way"),
        VocabularyWord(id: 339, word: "Acerbic", definition: "Sharp and forthright in speech"),
        VocabularyWord(id: 340, word: "Bellicose", definition: "Demonstrating aggression; warlike"),
        VocabularyWord(id: 341, word: "Contumacious", definition: "Stubbornly disobedient"),
        VocabularyWord(id: 342, word: "Dyspeptic", definition: "Bad-tempered or gloomy"),
        VocabularyWord(id: 343, word: "Eschatology", definition: "The part of theology concerned with death and destiny"),
        VocabularyWord(id: 344, word: "Fustian", definition: "Pompous or pretentious speech or writing"),
        VocabularyWord(id: 345, word: "Gossamer", definition: "Light, delicate, and insubstantial"),
        VocabularyWord(id: 346, word: "Hidebound", definition: "Unwilling to change because of tradition"),
        VocabularyWord(id: 347, word: "Insouciance", definition: "Casual lack of concern"),
        VocabularyWord(id: 348, word: "Jeremiad", definition: "A long, mournful complaint"),
        VocabularyWord(id: 349, word: "Limn", definition: "To depict or describe in detail"),
        VocabularyWord(id: 350, word: "Malediction", definition: "A curse"),
        VocabularyWord(id: 351, word: "Nefarious", definition: "Wicked or criminal"),
        VocabularyWord(id: 352, word: "Obsequious", definition: "Obedient to an excessive degree"),
        VocabularyWord(id: 353, word: "Perfidy", definition: "Deceitfulness; untrustworthiness"),
        VocabularyWord(id: 354, word: "Quiescence", definition: "A state of inactivity or dormancy"),
        VocabularyWord(id: 355, word: "Recumbent", definition: "Lying down"),
        VocabularyWord(id: 356, word: "Supine", definition: "Lying face upward; failing to act due to laziness"),
        VocabularyWord(id: 357, word: "Transmute", definition: "To change in form, nature, or substance"),
        VocabularyWord(id: 358, word: "Untrammeled", definition: "Not restricted or hampered"),
        VocabularyWord(id: 359, word: "Venal", definition: "Showing susceptibility to bribery"),
        VocabularyWord(id: 360, word: "Wizened", definition: "Shriveled or wrinkled with age"),
        VocabularyWord(id: 361, word: "Acuity", definition: "Sharpness of thought, vision, or hearing"),
        VocabularyWord(id: 362, word: "Bilious", definition: "Spiteful; bad-tempered"),
        VocabularyWord(id: 363, word: "Circumlocution", definition: "The use of many words where fewer would do"),
        VocabularyWord(id: 364, word: "Dolorous", definition: "Feeling or expressing great sorrow"),
    ]

    /// Returns the word for today based on the day of the year
    static func todaysWord() -> VocabularyWord {
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: Date()) ?? 1
        let index = (dayOfYear - 1) % words.count
        return words[index]
    }

    /// Returns the word for a specific date
    static func wordForDate(_ date: Date) -> VocabularyWord {
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: date) ?? 1
        let index = (dayOfYear - 1) % words.count
        return words[index]
    }
}
